# Translations template for nova.
# Copyright (C) 2012 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 2013.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2012-11-29 00:02+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: nova/context.py:62
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: nova/context.py:100
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: nova/crypto.py:46
msgid "Filename of root CA"
msgstr ""

#: nova/crypto.py:49
msgid "Filename of private key"
msgstr ""

#: nova/crypto.py:52
msgid "Filename of root Certificate Revocation List"
msgstr ""

#: nova/crypto.py:55
msgid "Where we keep our keys"
msgstr ""

#: nova/crypto.py:58
msgid "Where we keep our root CA"
msgstr ""

#: nova/crypto.py:61
msgid "Should we use a CA for each project?"
msgstr ""

#: nova/crypto.py:65
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: nova/crypto.py:70
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: nova/crypto.py:301
#, python-format
msgid "Flags path: %s"
msgstr ""

#: nova/exception.py:56
msgid "Unexpected error while running command."
msgstr ""

#: nova/exception.py:59
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: nova/exception.py:72
msgid "DB exception wrapped."
msgstr ""

#: nova/exception.py:129
msgid "An unknown exception occurred."
msgstr ""

#: nova/exception.py:150 nova/openstack/common/rpc/common.py:46
msgid "Exception in string format operation"
msgstr ""

#: nova/exception.py:160
msgid "Unknown"
msgstr ""

#: nova/exception.py:177
msgid "Failed to decrypt text"
msgstr ""

#: nova/exception.py:181
msgid "Virtual Interface creation failed"
msgstr ""

#: nova/exception.py:185
msgid "5 attempts to create virtual interfacewith unique mac address failed"
msgstr ""

#: nova/exception.py:190
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr ""

#: nova/exception.py:195
msgid "Not authorized."
msgstr ""

#: nova/exception.py:200
msgid "User does not have admin privileges"
msgstr ""

#: nova/exception.py:204
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: nova/exception.py:208
#, python-format
msgid "Image %(image_id)s is not active."
msgstr ""

#: nova/exception.py:212
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: nova/exception.py:216
msgid "Unacceptable parameters."
msgstr ""

#: nova/exception.py:221
#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr ""

#: nova/exception.py:225 nova/api/ec2/cloud.py:416 nova/api/ec2/cloud.py:441
#: nova/api/openstack/compute/contrib/keypairs.py:98 nova/compute/api.py:2287
msgid "Keypair data is invalid"
msgstr ""

#: nova/exception.py:229
msgid "The request is invalid."
msgstr ""

#: nova/exception.py:233
msgid "Invalid input received"
msgstr ""

#: nova/exception.py:237
msgid "Invalid volume"
msgstr ""

#: nova/exception.py:241 nova/api/openstack/compute/servers.py:1286
#: nova/api/openstack/compute/contrib/admin_actions.py:242
msgid "Invalid metadata"
msgstr ""

#: nova/exception.py:245
msgid "Invalid metadata size"
msgstr ""

#: nova/exception.py:249
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr ""

#: nova/exception.py:253 nova/api/ec2/cloud.py:598
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr ""

#: nova/exception.py:257
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: nova/exception.py:261
#, python-format
msgid "Invalid cidr %(cidr)s."
msgstr ""

#: nova/exception.py:265
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: nova/exception.py:272
#, python-format
msgid "%(err)s"
msgstr ""

#: nova/exception.py:276
#, python-format
msgid ""
"Cannot perform action '%(action)s' on aggregate %(aggregate_id)s. Reason:"
" %(reason)s."
msgstr ""

#: nova/exception.py:281
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:285
msgid "Sort key supplied was not valid."
msgstr ""

#: nova/exception.py:289
#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."
msgstr ""

#: nova/exception.py:294
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr ""

#: nova/exception.py:298
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr ""

#: nova/exception.py:302
#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr ""

#: nova/exception.py:306
msgid "Failed to suspend instance"
msgstr ""

#: nova/exception.py:310
msgid "Failed to resume server"
msgstr ""

#: nova/exception.py:314
msgid "Failed to reboot instance"
msgstr ""

#: nova/exception.py:318
msgid "Failed to terminate instance"
msgstr ""

#: nova/exception.py:322
msgid "Service is unavailable at this time."
msgstr ""

#: nova/exception.py:326
msgid "Insufficient compute resources."
msgstr ""

#: nova/exception.py:330
msgid "Compute service is unavailable at this time."
msgstr ""

#: nova/exception.py:334
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""

#: nova/exception.py:339
msgid "The supplied hypervisor type of is invalid."
msgstr ""

#: nova/exception.py:343
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr ""

#: nova/exception.py:348
#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""

#: nova/exception.py:353
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr ""

#: nova/exception.py:357
#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr ""

#: nova/exception.py:361
#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr ""

#: nova/exception.py:365
msgid "Unacceptable CPU info"
msgstr ""

#: nova/exception.py:369
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr ""

#: nova/exception.py:373
#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""

#: nova/exception.py:379
#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."
msgstr ""

#: nova/exception.py:386
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr ""

#: nova/exception.py:390
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:394
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:398
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr ""

#: nova/exception.py:402
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: nova/exception.py:406
msgid "Constraint not met."
msgstr ""

#: nova/exception.py:411
msgid "Resource could not be found."
msgstr ""

#: nova/exception.py:416
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: nova/exception.py:420
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: nova/exception.py:424
#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr ""

#: nova/exception.py:428
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: nova/exception.py:432
#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr ""

#: nova/exception.py:436
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: nova/exception.py:440
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: nova/exception.py:444
#, python-format
msgid ""
"Image %(image_id)s could not be found. The nova EC2 API assigns image ids"
" dynamically when they are listed for the first time. Have you listed "
"image ids since adding this image?"
msgstr ""

#: nova/exception.py:451
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:455
msgid "Cannot find SR to read/write VDI."
msgstr ""

#: nova/exception.py:459
#, python-format
msgid "Network %(network_id)s is duplicated."
msgstr ""

#: nova/exception.py:463
#, python-format
msgid "Network %(network_id)s is still in use."
msgstr ""

#: nova/exception.py:467
#, python-format
msgid "%(req)s is required to create a network."
msgstr ""

#: nova/exception.py:471
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr ""

#: nova/exception.py:475
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr ""

#: nova/exception.py:479
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr ""

#: nova/exception.py:483
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr ""

#: nova/exception.py:487
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr ""

#: nova/exception.py:491
msgid "No networks defined."
msgstr ""

#: nova/exception.py:495
#, python-format
msgid ""
"Either Network uuid %(network_uuid)s is not present or is not assigned to"
" the project %(project_id)s."
msgstr ""

#: nova/exception.py:500
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr ""

#: nova/exception.py:504
#, python-format
msgid "Port %(port_id)s is still in use."
msgstr ""

#: nova/exception.py:508
#, python-format
msgid "Port %(port_id)s could not be found."
msgstr ""

#: nova/exception.py:512
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr ""

#: nova/exception.py:516
#, python-format
msgid "Fixed ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:520
#, python-format
msgid "Instance %(instance_uuid)s has zero fixed ips."
msgstr ""

#: nova/exception.py:524
#, python-format
msgid "Network host %(host)s has zero fixed ips in network %(network_id)s."
msgstr ""

#: nova/exception.py:529
#, python-format
msgid "Instance %(instance_uuid)s doesn't have fixed ip '%(ip)s'."
msgstr ""

#: nova/exception.py:533
#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."
msgstr ""

#: nova/exception.py:538
#, python-format
msgid ""
"Fixed IP address %(address)s is already in use on instance "
"%(instance_uuid)s."
msgstr ""

#: nova/exception.py:543
#, python-format
msgid "More than one instance is associated with fixed ip address '%(address)s'."
msgstr ""

#: nova/exception.py:548
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr ""

#: nova/exception.py:552
msgid "Zero fixed ips available."
msgstr ""

#: nova/exception.py:556
msgid "Zero fixed ips could be found."
msgstr ""

#: nova/exception.py:565
#, python-format
msgid "Floating ip %(address)s already exists."
msgstr ""

#: nova/exception.py:569
#, python-format
msgid "Floating ip not found for id %(id)s."
msgstr ""

#: nova/exception.py:573
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr ""

#: nova/exception.py:577
#, python-format
msgid "Floating ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:581
#, python-format
msgid "Floating ip not found for host %(host)s."
msgstr ""

#: nova/exception.py:585
#, python-format
msgid "Multiple floating ips are found for address %(address)s."
msgstr ""

#: nova/exception.py:589
msgid "Floating ip pool not found."
msgstr ""

#: nova/exception.py:594
msgid "Zero floating ips available."
msgstr ""

#: nova/exception.py:599
#, python-format
msgid "Floating ip %(address)s is associated."
msgstr ""

#: nova/exception.py:603
#, python-format
msgid "Floating ip %(address)s is not associated."
msgstr ""

#: nova/exception.py:607
msgid "Zero floating ips exist."
msgstr ""

#: nova/exception.py:611
#, python-format
msgid "Interface %(interface)s not found."
msgstr ""

#: nova/exception.py:615
msgid "Cannot disassociate auto assigined floating ip"
msgstr ""

#: nova/exception.py:619
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr ""

#: nova/exception.py:623
#, python-format
msgid "Certificate %(certificate_id)s not found."
msgstr ""

#: nova/exception.py:627
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: nova/exception.py:631
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: nova/exception.py:635
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr ""

#: nova/exception.py:639
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: nova/exception.py:643
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: nova/exception.py:647
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""

#: nova/exception.py:652
msgid "Quota could not be found"
msgstr ""

#: nova/exception.py:656
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: nova/exception.py:660
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:664
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: nova/exception.py:668
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:672
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: nova/exception.py:676
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: nova/exception.py:680
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr ""

#: nova/exception.py:684
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""

#: nova/exception.py:689
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr ""

#: nova/exception.py:693
#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"
msgstr ""

#: nova/exception.py:698
#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""

#: nova/exception.py:703
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: nova/exception.py:707
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: nova/exception.py:712
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr ""

#: nova/exception.py:716
#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."
msgstr ""

#: nova/exception.py:722
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr ""

#: nova/exception.py:726
#, python-format
msgid "Console for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:730
#, python-format
msgid ""
"Console for instance %(instance_uuid)s in pool %(pool_id)s could not be "
"found."
msgstr ""

#: nova/exception.py:735
#, python-format
msgid "Invalid console type %(console_type)s"
msgstr ""

#: nova/exception.py:739
#, python-format
msgid "Instance type %(instance_type_id)s could not be found."
msgstr ""

#: nova/exception.py:743
#, python-format
msgid "Instance type with name %(instance_type_name)s could not be found."
msgstr ""

#: nova/exception.py:748
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr ""

#: nova/exception.py:752
#, python-format
msgid "Flavor access not found for %(flavor_id) / %(project_id) combination."
msgstr ""

#: nova/exception.py:757
#, python-format
msgid "Cell %(cell_id)s could not be found."
msgstr ""

#: nova/exception.py:761
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: nova/exception.py:765
#, python-format
msgid "Scheduler cost function %(cost_fn_str)s could not be found."
msgstr ""

#: nova/exception.py:770
#, python-format
msgid "Scheduler weight flag not found: %(flag_name)s"
msgstr ""

#: nova/exception.py:774
#, python-format
msgid "Instance %(instance_uuid)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:779
#, python-format
msgid ""
"Instance %(instance_uuid)s has no system metadata with key "
"%(metadata_key)s."
msgstr ""

#: nova/exception.py:784
#, python-format
msgid ""
"Instance Type %(instance_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: nova/exception.py:789
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: nova/exception.py:793
msgid "Zero files could be found."
msgstr ""

#: nova/exception.py:797
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""

#: nova/exception.py:802
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr ""

#: nova/exception.py:806
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: nova/exception.py:810
msgid "Action not allowed."
msgstr ""

#: nova/exception.py:814
msgid "Rotation is not allowed for snapshots"
msgstr ""

#: nova/exception.py:818
msgid "Rotation param is required for backup image_type"
msgstr ""

#: nova/exception.py:822
#, python-format
msgid "Key pair %(key_name)s already exists."
msgstr ""

#: nova/exception.py:826
#, python-format
msgid "Instance %(name)s already exists."
msgstr ""

#: nova/exception.py:830
#, python-format
msgid "Instance Type with name %(name)s already exists."
msgstr ""

#: nova/exception.py:834
#, python-format
msgid "Instance Type with ID %(flavor_id)s already exists."
msgstr ""

#: nova/exception.py:838
#, python-format
msgid ""
"Flavor access alreay exists for flavor %(flavor_id)s and project "
"%(project_id)s combination."
msgstr ""

#: nova/exception.py:843
#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr ""

#: nova/exception.py:847
#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr ""

#: nova/exception.py:851
msgid "Migration error"
msgstr ""

#: nova/exception.py:855
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: nova/exception.py:861
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: nova/exception.py:865
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: nova/exception.py:869
msgid "When resizing, instances must change flavor!"
msgstr ""

#: nova/exception.py:873
#, python-format
msgid "Resize error: %(reason)s"
msgstr ""

#: nova/exception.py:877
msgid "Image is larger than instance type allows"
msgstr ""

#: nova/exception.py:881
msgid "Instance type's memory is too small for requested image."
msgstr ""

#: nova/exception.py:885
msgid "Instance type's disk is too small for requested image."
msgstr ""

#: nova/exception.py:889
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""

#: nova/exception.py:893
msgid "Could not fetch bandwidth/cpu/disk metrics for this host."
msgstr ""

#: nova/exception.py:897
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: nova/exception.py:901
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: nova/exception.py:905
msgid "Quota exceeded"
msgstr ""

#: nova/exception.py:912
#, python-format
msgid ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used "
"%(used)d of %(allowed)d %(resource)s"
msgstr ""

#: nova/exception.py:917
msgid "Maximum number of floating ips exceeded"
msgstr ""

#: nova/exception.py:921
#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr ""

#: nova/exception.py:925
msgid "Personality file limit exceeded"
msgstr ""

#: nova/exception.py:929
msgid "Personality file path too long"
msgstr ""

#: nova/exception.py:933
msgid "Personality file content too long"
msgstr ""

#: nova/exception.py:937
msgid "Maximum number of key pairs exceeded"
msgstr ""

#: nova/exception.py:941
msgid "Maximum number of security groups or rules exceeded"
msgstr ""

#: nova/exception.py:945
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."
msgstr ""

#: nova/exception.py:950
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr ""

#: nova/exception.py:954
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr ""

#: nova/exception.py:958
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr ""

#: nova/exception.py:962
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:967
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr ""

#: nova/exception.py:971
msgid "Unable to create instance type"
msgstr ""

#: nova/exception.py:975
#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr ""

#: nova/exception.py:981
#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr ""

#: nova/exception.py:985
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: nova/exception.py:989
#, python-format
msgid "Marker %(marker)s could not be found."
msgstr ""

#: nova/exception.py:993
#, python-format
msgid "Invalid id: %(val)s (expecting \"i-...\")."
msgstr ""

#: nova/exception.py:997
#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr ""

#: nova/exception.py:1001
#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr ""

#: nova/exception.py:1005
#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr ""

#: nova/exception.py:1009
#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr ""

#: nova/exception.py:1013
#, python-format
msgid "Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr ""

#: nova/exception.py:1018
#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr ""

#: nova/exception.py:1023
#, python-format
msgid ""
"User data too large. User data must be no larger than %(maxsize)s bytes "
"once base64 encoded. Your data is %(length)d bytes"
msgstr ""

#: nova/exception.py:1029
msgid "User data needs to be valid base 64."
msgstr ""

#: nova/exception.py:1033
#, python-format
msgid ""
"unexpected task state: expecting %(expected)s but the actual state is "
"%(actual)s"
msgstr ""

#: nova/exception.py:1038
#, python-format
msgid "The CA file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1042
#, python-format
msgid "The CRL file for %(project)s could not be found"
msgstr ""

#: nova/manager.py:165
#, python-format
msgid "Skipping %(full_task_name)s, %(ticks_to_skip)s ticks left until next run"
msgstr ""

#: nova/manager.py:171
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: nova/manager.py:181
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: nova/manager.py:256
msgid "Notifying Schedulers of capabilities ..."
msgstr ""

#: nova/notifications.py:111 nova/notifications.py:151
msgid "Failed to send state update notification"
msgstr ""

#: nova/notifications.py:229
msgid "Failed to get nw_info"
msgstr ""

#: nova/policy.py:31
msgid "JSON file representing policy"
msgstr ""

#: nova/policy.py:34
msgid "Rule checked when requested rule is not found"
msgstr ""

#: nova/quota.py:719
#, python-format
msgid "Created reservations %(reservations)s"
msgstr ""

#: nova/quota.py:738
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: nova/quota.py:756
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: nova/service.py:173
msgid "Full set of CONF:"
msgstr ""

#: nova/service.py:180
#, python-format
msgid "%(flag)s : FLAG SET "
msgstr ""

#: nova/service.py:190 nova/service.py:288
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: nova/service.py:234
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: nova/service.py:270
msgid "Forking too fast, sleeping"
msgstr ""

#: nova/service.py:293
msgid "Unhandled exception"
msgstr ""

#: nova/service.py:300
#, python-format
msgid "Started child %d"
msgstr ""

#: nova/service.py:310
#, python-format
msgid "Starting %d workers"
msgstr ""

#: nova/service.py:324
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: nova/service.py:327
#, python-format
msgid "Child %(pid)d exited with status %(code)d"
msgstr ""

#: nova/service.py:330
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: nova/service.py:350
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: nova/service.py:361
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: nova/service.py:392
#, python-format
msgid "Starting %(topic)s node (version %(vcs_string)s)"
msgstr ""

#: nova/service.py:409 nova/openstack/common/rpc/service.py:47
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: nova/service.py:429
#, python-format
msgid "Join ServiceGroup membership for this service %s"
msgstr ""

#: nova/service.py:506
msgid "Service killed that has no database entry"
msgstr ""

#: nova/service.py:626
msgid "serve() can only be called once"
msgstr ""

#: nova/utils.py:174
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: nova/utils.py:185
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: nova/utils.py:209 nova/utils.py:287 nova/virt/powervm/common.py:82
#, python-format
msgid "Result was %s"
msgstr ""

#: nova/utils.py:222
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: nova/utils.py:262
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: nova/utils.py:264
msgid "Environment not supported over SSH"
msgstr ""

#: nova/utils.py:268
msgid "process_input not supported over SSH"
msgstr ""

#: nova/utils.py:303
#, python-format
msgid "debug in callback: %s"
msgstr ""

#: nova/utils.py:462
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: nova/utils.py:465
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: nova/utils.py:500
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: nova/utils.py:561
msgid "in looping call"
msgstr ""

#: nova/utils.py:621
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: nova/utils.py:750
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: nova/utils.py:779
#, python-format
msgid "Invalid server_string: %s"
msgstr ""

#: nova/utils.py:903
#, python-format
msgid "timefunc: '%(name)s' took %(total_time).2f secs"
msgstr ""

#: nova/utils.py:980
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: nova/utils.py:1090 nova/virt/configdrive.py:154
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: nova/wsgi.py:85
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:109
msgid "Stopping WSGI server."
msgstr ""

#: nova/wsgi.py:127
msgid "WSGI server has stopped."
msgstr ""

#: nova/wsgi.py:196
msgid "You must implement __call__"
msgstr ""

#: nova/wsgi.py:382
#, python-format
msgid "Loading app %(name)s from %(path)s"
msgstr ""

#: nova/api/auth.py:109
msgid "Invalid service catalog json."
msgstr ""

#: nova/api/auth.py:132
msgid "Sourcing roles from deprecated X-Role HTTP header"
msgstr ""

#: nova/api/sizelimit.py:50
msgid "Request is too large."
msgstr ""

#: nova/api/validator.py:138
#, python-format
msgid "%(key)s with value %(value)s failed validator %(name)s"
msgstr ""

#: nova/api/ec2/__init__.py:81
#, python-format
msgid "%(code)s: %(message)s"
msgstr ""

#: nova/api/ec2/__init__.py:104
#, python-format
msgid "FaultWrapper: %s"
msgstr ""

#: nova/api/ec2/__init__.py:179
msgid "Too many failed authentications."
msgstr ""

#: nova/api/ec2/__init__.py:189
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and"
" will be locked out for %(lock_mins)d minutes."
msgstr ""

#: nova/api/ec2/__init__.py:206
msgid "Signature not provided"
msgstr ""

#: nova/api/ec2/__init__.py:210
msgid "Access key not provided"
msgstr ""

#: nova/api/ec2/__init__.py:245 nova/api/ec2/__init__.py:260
msgid "Failure communicating with keystone"
msgstr ""

#: nova/api/ec2/__init__.py:259
#, python-format
msgid "Keystone failure: %s"
msgstr ""

#: nova/api/ec2/__init__.py:319
msgid "Timestamp failed validation."
msgstr ""

#: nova/api/ec2/__init__.py:339
#, python-format
msgid "action: %s"
msgstr ""

#: nova/api/ec2/__init__.py:341
#, python-format
msgid "arg: %(key)s\t\tval: %(value)s"
msgstr ""

#: nova/api/ec2/__init__.py:416
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: nova/api/ec2/__init__.py:488
#, python-format
msgid "InstanceNotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:494
#, python-format
msgid "VolumeNotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:500
#, python-format
msgid "SnapshotNotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:506
#, python-format
msgid "NotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:509
#, python-format
msgid "EC2APIError raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:517
#, python-format
msgid "KeyPairExists raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:521
#, python-format
msgid "InvalidParameterValue raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:525
#, python-format
msgid "InvalidPortRange raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:529
#, python-format
msgid "NotAuthorized raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:533
#, python-format
msgid "InvalidRequest raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:537
#, python-format
msgid "QuotaError raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:541
#, python-format
msgid "Invalid id: bogus (expecting \"i-...\"): %s"
msgstr ""

#: nova/api/ec2/__init__.py:550
#, python-format
msgid "Unexpected error raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:551
#, python-format
msgid "Environment: %s"
msgstr ""

#: nova/api/ec2/__init__.py:553 nova/api/metadata/handler.py:81
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: nova/api/ec2/apirequest.py:62
#, python-format
msgid "Unsupported API request: controller = %(controller)s, action = %(action)s"
msgstr ""

#: nova/api/ec2/cloud.py:364
#, python-format
msgid "Create snapshot of volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:390
#, python-format
msgid "Could not find key pair(s): %s"
msgstr ""

#: nova/api/ec2/cloud.py:406
#, python-format
msgid "Create key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:413 nova/api/ec2/cloud.py:438
#: nova/api/openstack/compute/contrib/keypairs.py:93
msgid "Quota exceeded, too many key pairs."
msgstr ""

#: nova/api/ec2/cloud.py:419 nova/api/ec2/cloud.py:444
#: nova/api/openstack/compute/contrib/keypairs.py:101
#, python-format
msgid "Key pair '%s' already exists."
msgstr ""

#: nova/api/ec2/cloud.py:428
#, python-format
msgid "Import key %s"
msgstr ""

#: nova/api/ec2/cloud.py:451
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:585 nova/api/ec2/cloud.py:706
msgid "Not enough parameters, need group_name or group_id"
msgstr ""

#: nova/api/ec2/cloud.py:590
#, python-format
msgid "%s Not enough parameters to build a valid rule"
msgstr ""

#: nova/api/ec2/cloud.py:628 nova/api/ec2/cloud.py:660
msgid "No rule for the specified parameters."
msgstr ""

#: nova/api/ec2/cloud.py:651
#, python-format
msgid "%s - This rule already exists in group"
msgstr ""

#: nova/api/ec2/cloud.py:717
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:793
#, python-format
msgid "Create volume from snapshot %s"
msgstr ""

#: nova/api/ec2/cloud.py:797 nova/api/openstack/compute/contrib/volumes.py:240
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/ec2/cloud.py:825
msgid "Delete Failed"
msgstr ""

#: nova/api/ec2/cloud.py:838
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: nova/api/ec2/cloud.py:846
msgid "Attach Failed."
msgstr ""

#: nova/api/ec2/cloud.py:859 nova/api/openstack/compute/contrib/volumes.py:419
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:865
msgid "Detach Volume Failed."
msgstr ""

#: nova/api/ec2/cloud.py:891 nova/api/ec2/cloud.py:948
#: nova/api/ec2/cloud.py:1484 nova/api/ec2/cloud.py:1499
#, python-format
msgid "attribute not supported: %s"
msgstr ""

#: nova/api/ec2/cloud.py:1013
#, python-format
msgid "vol = %s\n"
msgstr ""

#: nova/api/ec2/cloud.py:1164
msgid "Allocate address"
msgstr ""

#: nova/api/ec2/cloud.py:1168
msgid "No more floating IPs available"
msgstr ""

#: nova/api/ec2/cloud.py:1172
#, python-format
msgid "Release address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1177
msgid "Unable to release IP Address."
msgstr ""

#: nova/api/ec2/cloud.py:1180
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1188
msgid "Unable to associate IP Address, no fixed_ips."
msgstr ""

#: nova/api/ec2/cloud.py:1196
#: nova/api/openstack/compute/contrib/floating_ips.py:257
#, python-format
msgid "multiple fixed_ips exist, using the first: %s"
msgstr ""

#: nova/api/ec2/cloud.py:1205
msgid "Floating ip is already associated."
msgstr ""

#: nova/api/ec2/cloud.py:1208
msgid "l3driver call to add floating ip failed."
msgstr ""

#: nova/api/ec2/cloud.py:1211
msgid "Error, unable to associate floating ip."
msgstr ""

#: nova/api/ec2/cloud.py:1219
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1224
msgid "Floating ip is not associated."
msgstr ""

#: nova/api/ec2/cloud.py:1227
#: nova/api/openstack/compute/contrib/floating_ips.py:100
msgid "Cannot disassociate auto assigned floating ip"
msgstr ""

#: nova/api/ec2/cloud.py:1254
msgid "Image must be available"
msgstr ""

#: nova/api/ec2/cloud.py:1286
msgid "Going to start terminating instances"
msgstr ""

#: nova/api/ec2/cloud.py:1296
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: nova/api/ec2/cloud.py:1305
msgid "Going to stop instances"
msgstr ""

#: nova/api/ec2/cloud.py:1314
msgid "Going to start instances"
msgstr ""

#: nova/api/ec2/cloud.py:1405
#, python-format
msgid "De-registering image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1421
msgid "imageLocation is required"
msgstr ""

#: nova/api/ec2/cloud.py:1440
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1502
msgid "user or group not specified"
msgstr ""

#: nova/api/ec2/cloud.py:1504
msgid "only group \"all\" is supported"
msgstr ""

#: nova/api/ec2/cloud.py:1506
msgid "operation_type must be add or remove"
msgstr ""

#: nova/api/ec2/cloud.py:1508
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: nova/api/ec2/cloud.py:1521
#, python-format
msgid "Not allowed to modify attributes for image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1550
#, python-format
msgid ""
"Invalid value '%(ec2_instance_id)s' for instanceId. Instance does not "
"have a volume attached at root (%(root)s)"
msgstr ""

#: nova/api/ec2/cloud.py:1580
#, python-format
msgid "Couldn't stop instance with in %d sec"
msgstr ""

#: nova/api/ec2/cloud.py:1598
#, python-format
msgid "image of %(instance)s at %(now)s"
msgstr ""

#: nova/api/ec2/cloud.py:1631
msgid "Invalid CIDR"
msgstr ""

#: nova/api/ec2/ec2utils.py:188
msgid "Request must include either Timestamp or Expires, but cannot contain both"
msgstr ""

#: nova/api/ec2/ec2utils.py:208
msgid "Timestamp is invalid."
msgstr ""

#: nova/api/metadata/handler.py:79 nova/api/metadata/handler.py:86
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr ""

#: nova/api/openstack/__init__.py:51
#, python-format
msgid "Caught error: %s"
msgstr ""

#: nova/api/openstack/__init__.py:60 nova/api/openstack/wsgi.py:986
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: nova/api/openstack/__init__.py:135
msgid "Must specify an ExtensionManager class"
msgstr ""

#: nova/api/openstack/__init__.py:146
#, python-format
msgid "Extended resource: %s"
msgstr ""

#: nova/api/openstack/__init__.py:180
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: nova/api/openstack/__init__.py:185
#, python-format
msgid "Extension %(ext_name)s extending resource: %(collection)s"
msgstr ""

#: nova/api/openstack/common.py:101
#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. "
"Bad upgrade or db corrupted?"
msgstr ""

#: nova/api/openstack/common.py:140 nova/api/openstack/common.py:174
msgid "limit param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:143 nova/api/openstack/common.py:178
msgid "limit param must be positive"
msgstr ""

#: nova/api/openstack/common.py:168
msgid "offset param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:182
msgid "offset param must be positive"
msgstr ""

#: nova/api/openstack/common.py:217 nova/api/openstack/compute/servers.py:536
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: nova/api/openstack/common.py:257
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: nova/api/openstack/common.py:272
msgid "Image metadata limit exceeded"
msgstr ""

#: nova/api/openstack/common.py:280
msgid "Image metadata key cannot be blank"
msgstr ""

#: nova/api/openstack/common.py:283
msgid "Image metadata key too long"
msgstr ""

#: nova/api/openstack/common.py:286
msgid "Invalid image metadata"
msgstr ""

#: nova/api/openstack/common.py:337
#, python-format
msgid "Cannot '%(action)s' while instance is in %(attr)s %(state)s"
msgstr ""

#: nova/api/openstack/common.py:340
#, python-format
msgid "Instance is in an invalid state for '%(action)s'"
msgstr ""

#: nova/api/openstack/common.py:420
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: nova/api/openstack/common.py:422
msgid "Instance snapshots are not permitted at this time."
msgstr ""

#: nova/api/openstack/extensions.py:195
#, python-format
msgid "Loaded extension: %s"
msgstr ""

#: nova/api/openstack/extensions.py:234
#, python-format
msgid "Ext name: %s"
msgstr ""

#: nova/api/openstack/extensions.py:235
#, python-format
msgid "Ext alias: %s"
msgstr ""

#: nova/api/openstack/extensions.py:236
#, python-format
msgid "Ext description: %s"
msgstr ""

#: nova/api/openstack/extensions.py:238
#, python-format
msgid "Ext namespace: %s"
msgstr ""

#: nova/api/openstack/extensions.py:239
#, python-format
msgid "Ext updated: %s"
msgstr ""

#: nova/api/openstack/extensions.py:241
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: nova/api/openstack/extensions.py:255
#, python-format
msgid "Loading extension %s"
msgstr ""

#: nova/api/openstack/extensions.py:264
#, python-format
msgid "Calling extension factory %s"
msgstr ""

#: nova/api/openstack/extensions.py:276
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:357
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:381
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: nova/api/openstack/wsgi.py:199 nova/api/openstack/wsgi.py:619
msgid "cannot understand JSON"
msgstr ""

#: nova/api/openstack/wsgi.py:223
#: nova/api/openstack/compute/contrib/hosts.py:78
msgid "cannot understand XML"
msgstr ""

#: nova/api/openstack/wsgi.py:624
msgid "too many body keys"
msgstr ""

#: nova/api/openstack/wsgi.py:667
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:671
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:674
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:788
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:792
msgid "No Content-Type provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:796
msgid "Empty body provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:897
msgid "Invalid XML in request body"
msgstr ""

#: nova/api/openstack/wsgi.py:916
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:919 nova/api/openstack/wsgi.py:932
#: nova/api/openstack/compute/server_metadata.py:58
#: nova/api/openstack/compute/server_metadata.py:76
#: nova/api/openstack/compute/server_metadata.py:101
#: nova/api/openstack/compute/server_metadata.py:126
#: nova/api/openstack/compute/contrib/admin_actions.py:211
msgid "Malformed request body"
msgstr ""

#: nova/api/openstack/wsgi.py:929
msgid "Unsupported Content-Type"
msgstr ""

#: nova/api/openstack/wsgi.py:941
msgid "Malformed request url"
msgstr ""

#: nova/api/openstack/wsgi.py:989
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: nova/api/openstack/xmlutil.py:265
msgid "element is not a child"
msgstr ""

#: nova/api/openstack/xmlutil.py:414
msgid "root element selecting a list"
msgstr ""

#: nova/api/openstack/xmlutil.py:739
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: nova/api/openstack/xmlutil.py:858
msgid "subclasses must implement construct()!"
msgstr ""

#: nova/api/openstack/compute/extensions.py:31
msgid "Initializing extension manager."
msgstr ""

#: nova/api/openstack/compute/flavors.py:111
#, python-format
msgid "Invalid is_public filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:130
#, python-format
msgid "Invalid minRam filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:137
#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:36
#: nova/api/openstack/compute/images.py:144
#: nova/api/openstack/compute/images.py:159
msgid "Image not found."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:76
msgid "Incorrect request body format"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:80
#: nova/api/openstack/compute/server_metadata.py:80
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:79
msgid "Request body and URI mismatch"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:83
#: nova/api/openstack/compute/server_metadata.py:84
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:82
msgid "Request body contains too many items"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:109
msgid "Invalid metadata key"
msgstr ""

#: nova/api/openstack/compute/ips.py:71
msgid "Instance does not exist"
msgstr ""

#: nova/api/openstack/compute/ips.py:94
msgid "Instance is not a member of specified network"
msgstr ""

#: nova/api/openstack/compute/limits.py:145
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: nova/api/openstack/compute/limits.py:272
msgid "This request was rate-limited."
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:38
#: nova/api/openstack/compute/server_metadata.py:122
#: nova/api/openstack/compute/server_metadata.py:166
msgid "Server does not exist"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:148
#: nova/api/openstack/compute/server_metadata.py:159
msgid "Metadata item was not found"
msgstr ""

#: nova/api/openstack/compute/servers.py:450
#: nova/api/openstack/compute/servers.py:462
#: nova/api/openstack/compute/servers.py:555
#: nova/api/openstack/compute/servers.py:723
#: nova/api/openstack/compute/servers.py:984
#: nova/api/openstack/compute/servers.py:1087
#: nova/api/openstack/compute/servers.py:1237
msgid "Instance could not be found"
msgstr ""

#: nova/api/openstack/compute/servers.py:501
msgid "Invalid changes-since value"
msgstr ""

#: nova/api/openstack/compute/servers.py:520
msgid "Only administrators may list deleted instances"
msgstr ""

#: nova/api/openstack/compute/servers.py:539
msgid "Flavor could not be found"
msgstr ""

#: nova/api/openstack/compute/servers.py:562
msgid "Server name is not a string or unicode"
msgstr ""

#: nova/api/openstack/compute/servers.py:566
msgid "Server name is an empty string"
msgstr ""

#: nova/api/openstack/compute/servers.py:570
msgid "Server name must be less than 256 characters."
msgstr ""

#: nova/api/openstack/compute/servers.py:587
#, python-format
msgid "Bad personality format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:590
msgid "Bad personality format"
msgstr ""

#: nova/api/openstack/compute/servers.py:594
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:625
msgid "Unknown argment : port"
msgstr ""

#: nova/api/openstack/compute/servers.py:628
#, python-format
msgid "Bad port format: port uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:638
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:648
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:661
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr ""

#: nova/api/openstack/compute/servers.py:667
#, python-format
msgid "Bad network format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:670
msgid "Bad networks format"
msgstr ""

#: nova/api/openstack/compute/servers.py:696
msgid "Userdata content cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:703
msgid "accessIPv4 is not proper IPv4 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:710
msgid "accessIPv6 is not proper IPv6 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:739
msgid "Server name is not defined"
msgstr ""

#: nova/api/openstack/compute/servers.py:788
#: nova/api/openstack/compute/servers.py:894
msgid "Invalid flavorRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:828
msgid "min_count must be an integer value"
msgstr ""

#: nova/api/openstack/compute/servers.py:831
msgid "min_count must be > 0"
msgstr ""

#: nova/api/openstack/compute/servers.py:836
msgid "max_count must be an integer value"
msgstr ""

#: nova/api/openstack/compute/servers.py:839
msgid "max_count must be > 0"
msgstr ""

#: nova/api/openstack/compute/servers.py:842
msgid "min_count must be <= max_count"
msgstr ""

#: nova/api/openstack/compute/servers.py:891
msgid "Can not find requested image"
msgstr ""

#: nova/api/openstack/compute/servers.py:897
msgid "Invalid key_name provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:976
msgid "HostId cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:1002
#: nova/api/openstack/compute/servers.py:1022
msgid "Instance has not been resized."
msgstr ""

#: nova/api/openstack/compute/servers.py:1008
#, python-format
msgid "Error in confirm-resize %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:1028
#, python-format
msgid "Error in revert-resize %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:1041
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr ""

#: nova/api/openstack/compute/servers.py:1045
msgid "Missing argument 'type' for reboot"
msgstr ""

#: nova/api/openstack/compute/servers.py:1058
#, python-format
msgid "Error in reboot %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:1070
msgid "Unable to locate requested flavor."
msgstr ""

#: nova/api/openstack/compute/servers.py:1073
msgid "Resize requires a flavor change."
msgstr ""

#: nova/api/openstack/compute/servers.py:1097
msgid "Missing imageRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1106
msgid "Invalid imageRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:1115
msgid "Missing flavorRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1128
msgid "No adminPass was specified"
msgstr ""

#: nova/api/openstack/compute/servers.py:1132
#: nova/api/openstack/compute/servers.py:1334
msgid "Invalid adminPass"
msgstr ""

#: nova/api/openstack/compute/servers.py:1143
msgid "Unable to parse metadata key/value pairs."
msgstr ""

#: nova/api/openstack/compute/servers.py:1156
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1159
msgid "Resize requests require 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1177
#: nova/api/openstack/compute/contrib/aggregates.py:143
#: nova/api/openstack/compute/contrib/keypairs.py:78
#: nova/api/openstack/compute/contrib/networks.py:72
msgid "Invalid request body"
msgstr ""

#: nova/api/openstack/compute/servers.py:1182
msgid "Could not parse imageRef from request."
msgstr ""

#: nova/api/openstack/compute/servers.py:1244
msgid "Cannot find image for rebuild"
msgstr ""

#: nova/api/openstack/compute/servers.py:1277
msgid "createImage entity requires name attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1361
#, python-format
msgid "Removing options '%(unk_opt_str)s' from query"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:60
#, python-format
msgid "Compute.api::pause %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:77
#, python-format
msgid "Compute.api::unpause %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:94
#, python-format
msgid "compute.api::suspend %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:111
#, python-format
msgid "compute.api::resume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:127
#, python-format
msgid "Error in migrate %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:141
#, python-format
msgid "Compute.api::reset_network %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:154
#: nova/api/openstack/compute/contrib/admin_actions.py:170
#: nova/api/openstack/compute/contrib/admin_actions.py:186
#: nova/api/openstack/compute/contrib/admin_actions.py:314
#: nova/api/openstack/compute/contrib/multinic.py:41
#: nova/api/openstack/compute/contrib/rescue.py:45
msgid "Server not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:157
#, python-format
msgid "Compute.api::inject_network_info %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:173
#, python-format
msgid "Compute.api::lock %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:189
#, python-format
msgid "Compute.api::unlock %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:219
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:223
msgid "Malformed createBackup entity"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:229
msgid "createBackup attribute 'rotation' must be an integer"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:232
msgid "createBackup attribute 'rotation' must be greater than or equal to zero"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:248
#: nova/api/openstack/compute/contrib/console_output.py:47
#: nova/api/openstack/compute/contrib/server_diagnostics.py:47
#: nova/api/openstack/compute/contrib/server_start_stop.py:38
msgid "Instance not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:278
msgid "host and block_migration must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:286
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:304
#, python-format
msgid "Desired state must be specified.  Valid states are: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:317
#, python-format
msgid "Compute.api::resetState %s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:89
#, python-format
msgid "Cannot show aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:115
#, python-format
msgid "Cannot update aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:127
#, python-format
msgid "Cannot delete aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:140
#, python-format
msgid "Aggregates does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:153
#: nova/api/openstack/compute/contrib/aggregates.py:158
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:171
#: nova/api/openstack/compute/contrib/aggregates.py:175
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:195
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/certificates.py:73
msgid "Only root certificate can be retrieved."
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe.py:149
msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:52
msgid "os-getConsoleOutput malformed or missing from request body"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:59
msgid "Length in request body must be an integer value"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:67
msgid "Unable to get console"
msgstr ""

#: nova/api/openstack/compute/contrib/disk_config.py:43
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:42
#, python-format
msgid "Fixed IP %s has been deleted"
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:74
#, python-format
msgid "Fixed IP %s not found"
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:80
#: nova/api/openstack/compute/contrib/flavor_access.py:104
msgid "Flavor not found."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:109
msgid "Access list not available for public flavors."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:121
msgid "No request body"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:49
msgid "No Request Body"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:97
msgid "Floating ip is not associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:151
#: nova/api/openstack/compute/contrib/floating_ips.py:199
#, python-format
msgid "Floating ip not found for id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:184
#, python-format
msgid "No more floating ips in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:186
msgid "No more floating ips available."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:234
#: nova/api/openstack/compute/contrib/floating_ips.py:290
#: nova/api/openstack/compute/contrib/security_groups.py:414
msgid "Missing parameter dict"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:237
#: nova/api/openstack/compute/contrib/floating_ips.py:293
msgid "Address not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:244
msgid "No nw_info cache associated with instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:249
msgid "No fixed ips associated to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:265
msgid "floating ip is already associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:268
msgid "l3driver call to add floating ip failed"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:272
#: nova/api/openstack/compute/contrib/floating_ips.py:301
msgid "floating ip not found"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:275
msgid "Error. Unable to associate floating ip"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:150
#, python-format
msgid "/%s should be specified as single address(es) not in cidr format"
msgstr ""

#: nova/api/openstack/compute/contrib/fping.py:57
msgid "fping utility is not found."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:117
#, python-format
msgid "Host '%s' could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:146
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:150
#, python-format
msgid "Invalid mode: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:154
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:172
#, python-format
msgid "Putting host %(host)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:183
#, python-format
msgid "Setting host %(host)s to %(state)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:230
msgid "Describe-resource is admin only functionality"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:238
msgid "Host not found"
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:184
#: nova/api/openstack/compute/contrib/hypervisors.py:195
#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:203
msgid "Virt driver does not implement uptime function."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:218
#: nova/api/openstack/compute/contrib/hypervisors.py:232
#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr ""

#: nova/api/openstack/compute/contrib/instance_usage_audit_log.py:55
#, python-format
msgid "Invalid timestamp for date %s"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:52
msgid "Missing 'networkId' argument for addFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:68
msgid "Missing 'address' argument for removeFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:77
#, python-format
msgid "Unable to find address %r"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:69
#, python-format
msgid "Network does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:77
#, python-format
msgid "Disassociating network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:81
#: nova/api/openstack/compute/contrib/networks.py:98
#: nova/api/openstack/compute/contrib/networks.py:108
msgid "Network not found"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:94
#, python-format
msgid "Showing network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:104
#, python-format
msgid "Deleting network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:119
msgid "Missing network in body"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:123
msgid "Network label is required"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:127
msgid "Network cidr or cidr_v6 is required"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:129
#, python-format
msgid "Creating network with label %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:145
#, python-format
msgid "Associating network %(network)s with project %(project)s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:153
#, python-format
msgid "Cannot associate network %(network)s with project %(project)s: %(message)s"
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:63
msgid "Quota limit must be -1 or greater."
msgstr ""

#: nova/api/openstack/compute/contrib/scheduler_hints.py:41
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:221
msgid "Security group id should be integer"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:330
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:336
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:417
msgid "Security group not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:421
msgid "Security group name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:46
msgid "start instance"
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:55
msgid "stop instance"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:72
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:184
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:349
#: nova/api/openstack/compute/contrib/volumes.py:429
#, python-format
msgid "Instance %s is not attached."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:380
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:543
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:586
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:590
#, python-format
msgid "Invalid value '%s' for force. "
msgstr ""

#: nova/api/openstack/compute/views/servers.py:182
msgid "Instance has had its instance_type removed from the DB"
msgstr ""

#: nova/cloudpipe/pipelib.py:43
msgid "Instance type for vpn instances"
msgstr ""

#: nova/cloudpipe/pipelib.py:46
msgid "Template for cloudpipe instance boot script"
msgstr ""

#: nova/cloudpipe/pipelib.py:49
msgid "Network to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:52
msgid "Netmask to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:109
#, python-format
msgid "Launching VPN for %s"
msgstr ""

#: nova/common/sqlalchemyutils.py:68
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: nova/common/sqlalchemyutils.py:116
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: nova/compute/api.py:251
msgid "Cannot run any more instances of this type."
msgstr ""

#: nova/compute/api.py:258
#, python-format
msgid "Can only run %s more instances of this type."
msgstr ""

#: nova/compute/api.py:267
#, python-format
msgid ""
"%(overs)s quota exceeded for %(pid)s, tried to run %(min_count)s "
"instances. %(msg)s"
msgstr ""

#: nova/compute/api.py:287
#, python-format
msgid ""
"Quota exceeded for %(pid)s, tried to set %(num_metadata)s metadata "
"properties"
msgstr ""

#: nova/compute/api.py:297
msgid "Metadata property key blank"
msgstr ""

#: nova/compute/api.py:301
msgid "Metadata property key greater than 255 characters"
msgstr ""

#: nova/compute/api.py:305
msgid "Metadata property value greater than 255 characters"
msgstr ""

#: nova/compute/api.py:529
#, python-format
msgid "Going to run %s instances..."
msgstr ""

#: nova/compute/api.py:601
#, python-format
msgid "bdm %s"
msgstr ""

#: nova/compute/api.py:628
#, python-format
msgid "block_device_mapping %s"
msgstr ""

#: nova/compute/api.py:860
msgid "instance termination disabled"
msgstr ""

#: nova/compute/api.py:955
msgid "host for instance is down, deleting from database"
msgstr ""

#: nova/compute/api.py:999
msgid "Going to try to soft delete instance"
msgstr ""

#: nova/compute/api.py:1021
msgid "Going to try to terminate instance"
msgstr ""

#: nova/compute/api.py:1068
msgid "Going to try to stop instance"
msgstr ""

#: nova/compute/api.py:1082
msgid "Going to try to start instance"
msgstr ""

#: nova/compute/api.py:1149
#, python-format
msgid "Searching by: %s"
msgstr ""

#: nova/compute/api.py:1281
#, python-format
msgid "Image type not recognized %s"
msgstr ""

#: nova/compute/api.py:1390
#, python-format
msgid "snapshot for %s"
msgstr ""

#: nova/compute/api.py:1715
msgid "flavor_id is None. Assuming migration."
msgstr ""

#: nova/compute/api.py:1724
#, python-format
msgid ""
"Old instance type %(current_instance_type_name)s,  new instance type "
"%(new_instance_type_name)s"
msgstr ""

#: nova/compute/api.py:1766
#, python-format
msgid "%(overs)s quota exceeded for %(pid)s, tried to resize instance. %(msg)s"
msgstr ""

#: nova/compute/api.py:1942
msgid "Locking"
msgstr ""

#: nova/compute/api.py:1950
msgid "Unlocking"
msgstr ""

#: nova/compute/api.py:2018
msgid "Volume must be attached in order to detach."
msgstr ""

#: nova/compute/api.py:2103
#, python-format
msgid "Going to try to live migrate instance to %s"
msgstr ""

#: nova/compute/api.py:2260
msgid "Keypair name contains unsafe characters"
msgstr ""

#: nova/compute/api.py:2264
msgid "Keypair name must be between 1 and 255 characters long"
msgstr ""

#: nova/compute/api.py:2365
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr ""

#: nova/compute/api.py:2368
#, python-format
msgid "Security group %s cannot be empty."
msgstr ""

#: nova/compute/api.py:2376
#, python-format
msgid ""
"Value (%(value)s) for parameter Group%(property)s is invalid. Content "
"limited to '%(allowed)'."
msgstr ""

#: nova/compute/api.py:2382
#, python-format
msgid "Security group %s should not be greater than 255 characters."
msgstr ""

#: nova/compute/api.py:2402
msgid "Quota exceeded, too many security groups."
msgstr ""

#: nova/compute/api.py:2405
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/compute/api.py:2412
#, python-format
msgid "Security group %s already exists"
msgstr ""

#: nova/compute/api.py:2477
msgid "Security group is still in use"
msgstr ""

#: nova/compute/api.py:2485
msgid "Failed to update usages deallocating security group"
msgstr ""

#: nova/compute/api.py:2488
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/compute/api.py:2745
#, python-format
msgid "Rule (%s) not found"
msgstr ""

#: nova/compute/api.py:2754
msgid "Quota exceeded, too many security group rules."
msgstr ""

#: nova/compute/api.py:2757
#, python-format
msgid "Authorize security group ingress %s"
msgstr ""

#: nova/compute/api.py:2768
#, python-format
msgid "Revoke security group ingress %s"
msgstr ""

#: nova/compute/claims.py:94 nova/compute/claims.py:218
#, python-format
msgid "Aborting claim: %s"
msgstr ""

#: nova/compute/claims.py:116
#, python-format
msgid ""
"Attempting claim: memory %(memory_mb)d MB, disk %(disk_gb)d GB, VCPUs "
"%(vcpus)d"
msgstr ""

#: nova/compute/claims.py:128
msgid "Claim successful"
msgstr ""

#: nova/compute/claims.py:130
msgid "Claim failed"
msgstr ""

#: nova/compute/claims.py:135
msgid "Memory"
msgstr ""

#: nova/compute/claims.py:144
msgid "Disk"
msgstr ""

#: nova/compute/claims.py:153
msgid "CPU"
msgstr ""

#: nova/compute/claims.py:165
#, python-format
msgid "Total %(type_)s: %(total)d %(unit)s, used: %(used)d %(unit)s"
msgstr ""

#: nova/compute/claims.py:170
#, python-format
msgid "%(type_)s limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/claims.py:177
#, python-format
msgid "%(type_)s limit: %(limit)d %(unit)s, free: %(free)d %(unit)s"
msgstr ""

#: nova/compute/claims.py:184
#, python-format
msgid ""
"Unable to claim resources.  Free %(type_)s %(free)d %(unit)s < requested "
"%(requested)d %(unit)s"
msgstr ""

#: nova/compute/instance_types.py:65
msgid "names can only contain [a-zA-Z0-9_.- ]"
msgstr ""

#: nova/compute/instance_types.py:74
#, python-format
msgid "'%s' argument must be a positive integer"
msgstr ""

#: nova/compute/instance_types.py:82
msgid "'rxtx_factor' argument must be a positive float"
msgstr ""

#: nova/compute/instance_types.py:90
#, python-format
msgid "'%s' argument must be greater than 0"
msgstr ""

#: nova/compute/instance_types.py:100
msgid "is_public must be a boolean"
msgstr ""

#: nova/compute/instance_types.py:107
#, python-format
msgid "DB error: %s"
msgstr ""

#: nova/compute/instance_types.py:117
#, python-format
msgid "Instance type %s not found for deletion"
msgstr ""

#: nova/compute/manager.py:200
msgid "Possibly task preempted."
msgstr ""

#: nova/compute/manager.py:352
msgid "Instance has been destroyed from under us while trying to set it to ERROR"
msgstr ""

#: nova/compute/manager.py:380
#, python-format
msgid "Current state is %(drv_state)s, state in DB is %(db_state)s."
msgstr ""

#: nova/compute/manager.py:394
msgid "Rebooting instance after nova-compute restart."
msgstr ""

#: nova/compute/manager.py:408
msgid "Hypervisor driver does not support resume guests"
msgstr ""

#: nova/compute/manager.py:418
msgid "Hypervisor driver does not support firewall rules"
msgstr ""

#: nova/compute/manager.py:437
msgid "Checking state"
msgstr ""

#: nova/compute/manager.py:513
#, python-format
msgid "Setting up bdm %s"
msgstr ""

#: nova/compute/manager.py:585 nova/compute/manager.py:1807
#, python-format
msgid "No node specified, defaulting to %(node)s"
msgstr ""

#: nova/compute/manager.py:614
msgid "Failed to dealloc network for deleted instance"
msgstr ""

#: nova/compute/manager.py:637
#, python-format
msgid "Error: %s"
msgstr ""

#: nova/compute/manager.py:670 nova/compute/manager.py:1858
msgid "Error trying to reschedule"
msgstr ""

#: nova/compute/manager.py:687
msgid "Retry info not present, will not reschedule"
msgstr ""

#: nova/compute/manager.py:692
msgid "No request spec, will not reschedule"
msgstr ""

#: nova/compute/manager.py:698
#, python-format
msgid "Re-scheduling %(method)s: attempt %(num)d"
msgstr ""

#: nova/compute/manager.py:721
msgid "Instance build timed out. Set to error state."
msgstr ""

#: nova/compute/manager.py:751
msgid "Instance has already been created"
msgstr ""

#: nova/compute/manager.py:794
#, python-format
msgid ""
"image_id=%(image_id)s, image_size_bytes=%(size_bytes)d, "
"allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: nova/compute/manager.py:800
#, python-format
msgid ""
"Image '%(image_id)s' size %(size_bytes)d exceeded instance_type allowed "
"size %(allowed_size_bytes)d"
msgstr ""

#: nova/compute/manager.py:810
msgid "Starting instance..."
msgstr ""

#: nova/compute/manager.py:831
msgid "Instance failed network setup"
msgstr ""

#: nova/compute/manager.py:835
#, python-format
msgid "Instance network_info: |%s|"
msgstr ""

#: nova/compute/manager.py:848
msgid "Instance failed block device setup"
msgstr ""

#: nova/compute/manager.py:866
msgid "Instance failed to spawn"
msgstr ""

#: nova/compute/manager.py:890
msgid "Deallocating network for instance"
msgstr ""

#: nova/compute/manager.py:962
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: nova/compute/manager.py:993
#, python-format
msgid "Ignoring DiskNotFound: %s"
msgstr ""

#: nova/compute/manager.py:996
#, python-format
msgid "Ignoring VolumeNotFound: %s"
msgstr ""

#: nova/compute/manager.py:1003
#, python-format
msgid "terminating bdm %s"
msgstr ""

#: nova/compute/manager.py:1027
#, python-format
msgid "Ignoring volume cleanup failure due to %s"
msgstr ""

#: nova/compute/manager.py:1067 nova/compute/manager.py:2027
#: nova/compute/manager.py:3226
#, python-format
msgid "%s. Setting instance vm_state to ERROR"
msgstr ""

#: nova/compute/manager.py:1201
msgid "Rebuilding instance"
msgstr ""

#: nova/compute/manager.py:1284
msgid "Rebooting instance"
msgstr ""

#: nova/compute/manager.py:1308
#, python-format
msgid ""
"trying to reboot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:1317
#, python-format
msgid "Cannot reboot instance: %(exc)s"
msgstr ""

#: nova/compute/manager.py:1354
msgid "instance snapshotting"
msgstr ""

#: nova/compute/manager.py:1360
#, python-format
msgid ""
"trying to snapshot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:1413
#, python-format
msgid "Found %(num_images)d images (rotation: %(rotation)d)"
msgstr ""

#: nova/compute/manager.py:1420
#, python-format
msgid "Rotating out %d backups"
msgstr ""

#: nova/compute/manager.py:1425
#, python-format
msgid "Deleting image %s"
msgstr ""

#: nova/compute/manager.py:1456
#, python-format
msgid "Failed to set admin password. Instance %s is not running"
msgstr ""

#: nova/compute/manager.py:1463
msgid "Root password set"
msgstr ""

#: nova/compute/manager.py:1473
msgid "set_admin_password is not implemented by this driver."
msgstr ""

#: nova/compute/manager.py:1489
#, python-format
msgid "set_admin_password failed: %s"
msgstr ""

#: nova/compute/manager.py:1497
msgid "error setting admin password"
msgstr ""

#: nova/compute/manager.py:1512
#, python-format
msgid ""
"trying to inject a file into a non-running (state: "
"%(current_power_state)s expected: %(expected_state)s)"
msgstr ""

#: nova/compute/manager.py:1516
#, python-format
msgid "injecting file to %(path)s"
msgstr ""

#: nova/compute/manager.py:1537
msgid ""
"Unable to find a different image to use for rescue VM, using instance's "
"current image"
msgstr ""

#: nova/compute/manager.py:1550
msgid "Rescuing"
msgstr ""

#: nova/compute/manager.py:1581
msgid "Unrescuing"
msgstr ""

#: nova/compute/manager.py:1602
#, python-format
msgid "Changing instance metadata according to %(diff)r"
msgstr ""

#: nova/compute/manager.py:1774
msgid "Instance has no source host"
msgstr ""

#: nova/compute/manager.py:1780
msgid "destination same as source!"
msgstr ""

#: nova/compute/manager.py:1789
msgid "Migrating"
msgstr ""

#: nova/compute/manager.py:2024
#, python-format
msgid "Failed to rollback quota for failed finish_resize: %(qr_error)s"
msgstr ""

#: nova/compute/manager.py:2080
msgid "Pausing"
msgstr ""

#: nova/compute/manager.py:2097
msgid "Unpausing"
msgstr ""

#: nova/compute/manager.py:2135
msgid "Retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:2165
msgid "Resuming"
msgstr ""

#: nova/compute/manager.py:2187
msgid "Reset network"
msgstr ""

#: nova/compute/manager.py:2192
msgid "Inject network info"
msgstr ""

#: nova/compute/manager.py:2195
#, python-format
msgid "network_info to inject: |%s|"
msgstr ""

#: nova/compute/manager.py:2212
msgid "Get console output"
msgstr ""

#: nova/compute/manager.py:2237
msgid "Getting vnc console"
msgstr ""

#: nova/compute/manager.py:2265
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2309
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2318
#, python-format
msgid ""
"Failed to connect to volume %(volume_id)s while attaching at "
"%(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2333
#, python-format
msgid "Failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:2362
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:2366
msgid "Detaching volume from unknown instance"
msgstr ""

#: nova/compute/manager.py:2379
#, python-format
msgid "Faild to detach volume %(volume_id)s from %(mp)s"
msgstr ""

#: nova/compute/manager.py:2423
#, python-format
msgid "Host %(host)s not found"
msgstr ""

#: nova/compute/manager.py:2483
msgid "Instance has no volume."
msgstr ""

#: nova/compute/manager.py:2543
#, python-format
msgid "Pre live migration failed at  %(dest)s"
msgstr ""

#: nova/compute/manager.py:2569
msgid "_post_live_migration() is started.."
msgstr ""

#: nova/compute/manager.py:2618
#, python-format
msgid "Migrating instance to %(dest)s finished successfully."
msgstr ""

#: nova/compute/manager.py:2620
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: nova/compute/manager.py:2634
msgid "Post operation of migration started"
msgstr ""

#: nova/compute/manager.py:2768
msgid "Updated the info_cache for instance"
msgstr ""

#: nova/compute/manager.py:2797
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: nova/compute/manager.py:2803
#, python-format
msgid "Setting migration %(migration_id)s to error: %(reason)s"
msgstr ""

#: nova/compute/manager.py:2812
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/compute/manager.py:2819
#, python-format
msgid "Instance %(instance_uuid)s not found"
msgstr ""

#: nova/compute/manager.py:2823
msgid "In ERROR state"
msgstr ""

#: nova/compute/manager.py:2830
#, python-format
msgid "In states %(vm_state)s/%(task_state)s, notRESIZED/None"
msgstr ""

#: nova/compute/manager.py:2838
#, python-format
msgid "Error auto-confirming resize: %(e)s. Will retry later."
msgstr ""

#: nova/compute/manager.py:2855
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""

#: nova/compute/manager.py:2873
#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr ""

#: nova/compute/manager.py:2896
msgid "Updating bandwidth usage cache"
msgstr ""

#: nova/compute/manager.py:2962
msgid "Updating host status"
msgstr ""

#: nova/compute/manager.py:2990
#, python-format
msgid ""
"Found %(num_db_instances)s in the database and %(num_vm_instances)s on "
"the hypervisor."
msgstr ""

#: nova/compute/manager.py:2996 nova/compute/manager.py:3034
msgid "During sync_power_state the instance has a pending task. Skip."
msgstr ""

#: nova/compute/manager.py:3021
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to"
" host %(dst)s"
msgstr ""

#: nova/compute/manager.py:3058
msgid "Instance shutdown by itself. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:3070 nova/compute/manager.py:3081
#: nova/compute/manager.py:3095
msgid "error during stop() in sync_power_state."
msgstr ""

#: nova/compute/manager.py:3075
msgid "Instance is paused or suspended unexpectedly. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:3088
msgid "Instance is not stopped. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:3104
msgid "Instance is not (soft-)deleted."
msgstr ""

#: nova/compute/manager.py:3112
msgid "CONF.reclaim_instance_interval <= 0, skipping..."
msgstr ""

#: nova/compute/manager.py:3125
msgid "Reclaiming deleted instance"
msgstr ""

#: nova/compute/manager.py:3180
#, python-format
msgid ""
"Detected instance with name label '%(name)s' which is marked as DELETED "
"but still present on host."
msgstr ""

#: nova/compute/manager.py:3187
#, python-format
msgid ""
"Destroying instance with name label '%(name)s' which is marked as DELETED"
" but still present on host."
msgstr ""

#: nova/compute/manager.py:3194
#, python-format
msgid "Unrecognized value '%(action)s' for CONF.running_deleted_instance_action"
msgstr ""

#: nova/compute/resource_tracker.py:91
msgid ""
"Host field should not be set on the instance until resources have been "
"claimed."
msgstr ""

#: nova/compute/resource_tracker.py:96
msgid ""
"Node field should be not be set on the instance until resources have been"
" claimed."
msgstr ""

#: nova/compute/resource_tracker.py:242
msgid "Auditing locally available compute resources"
msgstr ""

#: nova/compute/resource_tracker.py:246
msgid ""
"Virt driver does not support 'get_available_resource'  Compute tracking "
"is disabled."
msgstr ""

#: nova/compute/resource_tracker.py:292
#, python-format
msgid "Compute_service record created for %s "
msgstr ""

#: nova/compute/resource_tracker.py:297
#, python-format
msgid "Compute_service record updated for %s "
msgstr ""

#: nova/compute/resource_tracker.py:310
#, python-format
msgid "No service record for host %s"
msgstr ""

#: nova/compute/resource_tracker.py:320
#, python-format
msgid "Hypervisor: free ram (MB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:321
#, python-format
msgid "Hypervisor: free disk (GB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:326
#, python-format
msgid "Hypervisor: free VCPUs: %s"
msgstr ""

#: nova/compute/resource_tracker.py:328
msgid "Hypervisor: VCPU information unavailable"
msgstr ""

#: nova/compute/resource_tracker.py:335
#, python-format
msgid "Free ram (MB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:336
#, python-format
msgid "Free disk (GB): %s"
msgstr ""

#: nova/compute/resource_tracker.py:341
#, python-format
msgid "Free VCPUS: %s"
msgstr ""

#: nova/compute/resource_tracker.py:343
msgid "Free VCPU information unavailable"
msgstr ""

#: nova/compute/resource_tracker.py:381
#, python-format
msgid "Updating from migration %s"
msgstr ""

#: nova/compute/resource_tracker.py:439
msgid "Instance not resizing, skipping migration."
msgstr ""

#: nova/compute/resource_tracker.py:507
#, python-format
msgid "Missing keys: %s"
msgstr ""

#: nova/compute/rpcapi.py:44
msgid "No compute host specified"
msgstr ""

#: nova/compute/rpcapi.py:47
#, python-format
msgid "Unable to find host for Instance %s"
msgstr ""

#: nova/compute/utils.py:94
#, python-format
msgid "Using %(prefix)s instead of %(req_prefix)s"
msgstr ""

#: nova/conductor/manager.py:47
#, python-format
msgid "Instance update attempted for '%(key)s' on %(instance_uuid)s"
msgstr ""

#: nova/console/manager.py:80 nova/console/vmrc_manager.py:62
msgid "Adding console"
msgstr ""

#: nova/console/manager.py:101 nova/console/vmrc_manager.py:114
#, python-format
msgid "Tried to remove non-existent console %(console_id)s."
msgstr ""

#: nova/console/vmrc_manager.py:117
#, python-format
msgid "Removing console %(console_id)s."
msgstr ""

#: nova/console/xvp.py:99
msgid "Rebuilding xvp conf"
msgstr ""

#: nova/console/xvp.py:117
#, python-format
msgid "Re-wrote %s"
msgstr ""

#: nova/console/xvp.py:122
msgid "Stopping xvp"
msgstr ""

#: nova/console/xvp.py:135
msgid "Starting xvp"
msgstr ""

#: nova/console/xvp.py:142
#, python-format
msgid "Error starting xvp: %s"
msgstr ""

#: nova/console/xvp.py:145
msgid "Restarting xvp"
msgstr ""

#: nova/console/xvp.py:147
msgid "xvp not running..."
msgstr ""

#: nova/consoleauth/manager.py:70
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s)"
msgstr ""

#: nova/consoleauth/manager.py:75
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s)"
msgstr ""

#: nova/db/sqlalchemy/api.py:183 nova/virt/baremetal/db/sqlalchemy/api.py:68
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: nova/db/sqlalchemy/api.py:1373
#, python-format
msgid ""
"Unknown osapi_compute_unique_server_name_scope value: %s Flag must be "
"empty, \"global\" or \"project\""
msgstr ""

#: nova/db/sqlalchemy/api.py:2730
#, python-format
msgid "Change will make usage less than 0 for the following resources: %(unders)s"
msgstr ""

#: nova/db/sqlalchemy/migration.py:71
#: nova/virt/baremetal/db/sqlalchemy/migration.py:69
msgid "version should be an integer"
msgstr ""

#: nova/db/sqlalchemy/migration.py:98
#: nova/virt/baremetal/db/sqlalchemy/migration.py:96
msgid "Upgrade DB using Essex release first."
msgstr ""

#: nova/db/sqlalchemy/session.py:299
#, python-format
msgid "Got mysql server has gone away: %s"
msgstr ""

#: nova/db/sqlalchemy/session.py:340
msgid "Using mysql/eventlet db_pool."
msgstr ""

#: nova/db/sqlalchemy/session.py:384
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/133_folsom.py:62
msgid "Exception while seeding instance_types table"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/133_folsom.py:927
msgid "Exception while creating table."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/133_folsom.py:1225
msgid "Downgrade from Folsom is unsupported."
msgstr ""

#: nova/image/glance.py:147
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""

#: nova/image/s3.py:312
#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:329
#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:339
#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:349
#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:373
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: nova/image/s3.py:380
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: nova/image/s3.py:391
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: nova/image/s3.py:403
msgid "Unsafe filenames in image"
msgstr ""

#: nova/ipv6/account_identifier.py:38 nova/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:40 nova/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:42
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr ""

#: nova/network/api.py:51
msgid "instance is a required argument to use @refresh_cache"
msgstr ""

#: nova/network/api.py:77
msgid "Failed storing info cache"
msgstr ""

#: nova/network/api.py:78
#, python-format
msgid "args: %s"
msgstr ""

#: nova/network/api.py:79
#, python-format
msgid "kwargs: %s"
msgstr ""

#: nova/network/api.py:170
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""

#: nova/network/ldapdns.py:97
#, python-format
msgid ""
"Found multiple matches for domain %(domain)s.\n"
"%(entry)s"
msgstr ""

#: nova/network/ldapdns.py:124
#, python-format
msgid "Unable to dequalify.  %(name)s is not in %(domain)s.\n"
msgstr ""

#: nova/network/ldapdns.py:319
msgid "This driver only supports type 'a' entries."
msgstr ""

#: nova/network/ldapdns.py:362
msgid "This shouldn't be getting called except during testing."
msgstr ""

#: nova/network/linux_net.py:186
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: nova/network/linux_net.py:221
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: nova/network/linux_net.py:246
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: nova/network/linux_net.py:381
msgid "IPTablesManager.apply completed with success"
msgstr ""

#: nova/network/linux_net.py:587
#, python-format
msgid "arping error for ip %s"
msgstr ""

#: nova/network/linux_net.py:798
#, python-format
msgid "Pid %d is stale, skip killing dnsmasq"
msgstr ""

#: nova/network/linux_net.py:838
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr ""

#: nova/network/linux_net.py:840
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr ""

#: nova/network/linux_net.py:903
#, python-format
msgid "killing radvd threw %s"
msgstr ""

#: nova/network/linux_net.py:905
#, python-format
msgid "Pid %d is stale, relaunching radvd"
msgstr ""

#: nova/network/linux_net.py:1036
#, python-format
msgid "Error clearing stale veth %s"
msgstr ""

#: nova/network/linux_net.py:1139
#, python-format
msgid "Starting VLAN inteface %s"
msgstr ""

#: nova/network/linux_net.py:1178
#, python-format
msgid "Starting Bridge %s"
msgstr ""

#: nova/network/linux_net.py:1190
#, python-format
msgid "Adding interface %(interface)s to bridge %(bridge)s"
msgstr ""

#: nova/network/linux_net.py:1223
#, python-format
msgid "Failed to add interface: %s"
msgstr ""

#: nova/network/linux_net.py:1360
#, python-format
msgid "Starting bridge %s "
msgstr ""

#: nova/network/linux_net.py:1368
#, python-format
msgid "Done starting bridge %s"
msgstr ""

#: nova/network/linux_net.py:1387
#, python-format
msgid "Failed unplugging gateway interface '%s'"
msgstr ""

#: nova/network/linux_net.py:1389
#, python-format
msgid "Unplugged gateway interface '%s'"
msgstr ""

#: nova/network/manager.py:302
#, python-format
msgid "Fixed ip %(fixed_ip_id)s not found"
msgstr ""

#: nova/network/manager.py:311 nova/network/manager.py:571
#, python-format
msgid "Interface %(interface)s not found"
msgstr ""

#: nova/network/manager.py:326
#, python-format
msgid "floating IP allocation for instance |%s|"
msgstr ""

#: nova/network/manager.py:390
msgid "Floating IP is not associated. Ignore."
msgstr ""

#: nova/network/manager.py:408
#, python-format
msgid "Address |%(address)s| is not allocated"
msgstr ""

#: nova/network/manager.py:412
#, python-format
msgid "Address |%(address)s| is not allocated to your project |%(project)s|"
msgstr ""

#: nova/network/manager.py:433
#, python-format
msgid "Quota exceeded for %(pid)s, tried to allocate floating IP"
msgstr ""

#: nova/network/manager.py:494
msgid "Failed to update usages deallocating floating IP"
msgstr ""

#: nova/network/manager.py:700
#, python-format
msgid "Starting migration network for instance %(instance_uuid)s"
msgstr ""

#: nova/network/manager.py:707
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will notmigrate it "
msgstr ""

#: nova/network/manager.py:737
#, python-format
msgid "Finishing migration network for instance %(instance_uuid)s"
msgstr ""

#: nova/network/manager.py:745
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will notsetup it."
msgstr ""

#: nova/network/manager.py:792
#, python-format
msgid ""
"Database inconsistency: DNS domain |%s| is registered in the Nova db but "
"not visible to either the floating or instance DNS driver. It will be "
"ignored."
msgstr ""

#: nova/network/manager.py:838
#, python-format
msgid "Domain |%(domain)s| already exists, changing zone to |%(av_zone)s|."
msgstr ""

#: nova/network/manager.py:848
#, python-format
msgid "Domain |%(domain)s| already exists, changing project to |%(project)s|."
msgstr ""

#: nova/network/manager.py:963
#, python-format
msgid "Disassociated %s stale fixed ip(s)"
msgstr ""

#: nova/network/manager.py:967
msgid "setting network host"
msgstr ""

#: nova/network/manager.py:1094
msgid "network allocations"
msgstr ""

#: nova/network/manager.py:1099
#, python-format
msgid "networks retrieved for instance: |%(networks)s|"
msgstr ""

#: nova/network/manager.py:1129
msgid "network deallocation for instance"
msgstr ""

#: nova/network/manager.py:1356
#, python-format
msgid ""
"instance-dns-zone is |%(domain)s|, which is in availability zone "
"|%(zone)s|. Instance is in zone |%(zone2)s|. No DNS record will be "
"created."
msgstr ""

#: nova/network/manager.py:1445
#, python-format
msgid "Unable to release %s because vif doesn't exist."
msgstr ""

#: nova/network/manager.py:1462
#, python-format
msgid "Leased IP |%(address)s|"
msgstr ""

#: nova/network/manager.py:1466
#, python-format
msgid "IP %s leased that is not associated"
msgstr ""

#: nova/network/manager.py:1474
#, python-format
msgid "IP |%s| leased that isn't allocated"
msgstr ""

#: nova/network/manager.py:1479
#, python-format
msgid "Released IP |%(address)s|"
msgstr ""

#: nova/network/manager.py:1483
#, python-format
msgid "IP %s released that is not associated"
msgstr ""

#: nova/network/manager.py:1486
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: nova/network/manager.py:1505
#, python-format
msgid "%s must be an integer"
msgstr ""

#: nova/network/manager.py:1529
msgid "Maximum allowed length for 'label' is 255."
msgstr ""

#: nova/network/manager.py:1549
#, python-format
msgid ""
"Subnet(s) too large, defaulting to /%s.  To override, specify "
"network_size flag."
msgstr ""

#: nova/network/manager.py:1630
msgid "cidr already in use"
msgstr ""

#: nova/network/manager.py:1633
#, python-format
msgid "requested cidr (%(cidr)s) conflicts with existing supernet (%(super)s)"
msgstr ""

#: nova/network/manager.py:1644
#, python-format
msgid ""
"requested cidr (%(cidr)s) conflicts with existing smaller cidr "
"(%(smaller)s)"
msgstr ""

#: nova/network/manager.py:1701
msgid "Network already exists!"
msgstr ""

#: nova/network/manager.py:1721
#, python-format
msgid "Network must be disassociated from project %s before delete"
msgstr ""

#: nova/network/manager.py:2191
msgid ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"
msgstr ""

#: nova/network/manager.py:2198
#, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s. Network size"
" is %(network_size)s"
msgstr ""

#: nova/network/minidns.py:67
msgid "This driver only supports type 'a'"
msgstr ""

#: nova/network/model.py:337
msgid "v4 subnets are required for legacy nw_info"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:71
msgid "Error creating network entry"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:86
#, python-format
msgid "No network with net_id = %s"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:252
#, python-format
msgid "No fixed IPs to deallocate for vif %s"
msgstr ""

#: nova/network/quantumv2/__init__.py:41
msgid "_get_auth_token() failed"
msgstr ""

#: nova/network/quantumv2/api.py:102
#, python-format
msgid "allocate_for_instance() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:105
#, python-format
msgid "empty project id for instance %s"
msgstr ""

#: nova/network/quantumv2/api.py:158
#, python-format
msgid "Fail to delete port %(portid)s with failure: %(exception)s"
msgstr ""

#: nova/network/quantumv2/api.py:170
#, python-format
msgid "deallocate_for_instance() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:179
#, python-format
msgid "Failed to delete quantum port %(portid)s "
msgstr ""

#: nova/network/quantumv2/api.py:189
#, python-format
msgid "get_instance_nw_info() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:204
#, python-format
msgid "validate_networks() for %s"
msgstr ""

#: nova/network/quantumv2/api.py:456
#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr ""

#: nova/openstack/common/lockutils.py:97
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: nova/openstack/common/lockutils.py:183
#, python-format
msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: nova/openstack/common/lockutils.py:187
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: nova/openstack/common/lockutils.py:215
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr ""

#: nova/openstack/common/log.py:177
#, python-format
msgid "Deprecated Config: %s"
msgstr ""

#: nova/openstack/common/log.py:309
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: nova/openstack/common/log.py:467
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: nova/openstack/common/policy.py:394
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: nova/openstack/common/policy.py:404
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: nova/openstack/common/policy.py:679
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: nova/openstack/common/notifier/api.py:125
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: nova/openstack/common/notifier/api.py:141
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: nova/openstack/common/notifier/api.py:170
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: nova/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr ""

#: nova/openstack/common/notifier/rpc_notifier.py:45
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: nova/openstack/common/plugin/pluginmanager.py:64
#, python-format
msgid "Failed to load plugin %(plug)s: %(exc)s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:209
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:253
#, python-format
msgid "received %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:259
#, python-format
msgid "no method for message: %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:260
#, python-format
msgid "No method for message: %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:286
msgid "Exception during message handling"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:352
#, python-format
msgid "Making asynchronous call on %s ..."
msgstr ""

#: nova/openstack/common/rpc/amqp.py:355
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: nova/openstack/common/rpc/amqp.py:377
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: nova/openstack/common/rpc/amqp.py:385
msgid "Making asynchronous fanout cast..."
msgstr ""

#: nova/openstack/common/rpc/amqp.py:411
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: nova/openstack/common/rpc/common.py:34
msgid "An unknown RPC related exception occurred."
msgstr ""

#: nova/openstack/common/rpc/common.py:64
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: nova/openstack/common/rpc/common.py:81
msgid "Timeout while waiting on RPC response."
msgstr ""

#: nova/openstack/common/rpc/common.py:85
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: nova/openstack/common/rpc/common.py:89
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: nova/openstack/common/rpc/common.py:206
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:168
#: nova/openstack/common/rpc/impl_qpid.py:126
msgid "Failed to process message... skipping it."
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:469
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:491
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:528
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:544
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:596
#: nova/openstack/common/rpc/impl_qpid.py:381
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:614
#: nova/openstack/common/rpc/impl_qpid.py:396
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:618
#: nova/openstack/common/rpc/impl_qpid.py:400
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_kombu.py:652
#: nova/openstack/common/rpc/impl_qpid.py:430
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:330
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:338
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:350
msgid "Re-established AMQP queues"
msgstr ""

#: nova/openstack/common/rpc/impl_qpid.py:408
msgid "Error processing message.  Skipping it."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:89
msgid "JSON serialization failed."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:97
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:133
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:134
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:135
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:143
msgid "Could not open socket."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:155
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:193
msgid "You cannot recv on this socket."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:198
msgid "You cannot send on this socket."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:251
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:276
msgid "Sending reply"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:344
msgid "Registering reactor"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:356
msgid "In reactor registered"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:371
msgid "Out reactor registered"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:375
msgid "Consuming socket"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:422
#, python-format
msgid "CONSUMER GOT %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:432
#, python-format
msgid "->response->%s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:442
#, python-format
msgid "Created topic proxy: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:449
#, python-format
msgid "ROUTER RELAY-OUT START %(data)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:451
#, python-format
msgid "ROUTER RELAY-OUT SUCCEEDED %(data)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:467
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:469
#, python-format
msgid "ROUTER RELAY-OUT %(data)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:495
#, python-format
msgid "Create Consumer for topic (%(topic)s)"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:511
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:554
msgid "Creating payload"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:567
msgid "Creating queue socket for reply waiter"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:578
msgid "Sending cast"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:581
msgid "Cast sent; Waiting reply"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:584
#, python-format
msgid "Received message: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:585
msgid "Unpacking response"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:612
#, python-format
msgid "%(msg)s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:615
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:619
msgid "No matchmaker results. Not casting."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:709
msgid ""
"Matchmaker could not be loaded.\n"
"rpc_zmq_matchmaker is not a class."
msgstr ""

#: nova/openstack/common/rpc/impl_zmq.py:711
msgid "Error loading Matchmaker."
msgstr ""

#: nova/openstack/common/rpc/matchmaker.py:45
msgid "Match not found by MatchMaker."
msgstr ""

#: nova/openstack/common/rpc/matchmaker.py:177
#: nova/openstack/common/rpc/matchmaker.py:195
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: nova/scheduler/chance.py:50
msgid "Is the appropriate service running?"
msgstr ""

#: nova/scheduler/chance.py:55
msgid "Could not find another compute"
msgstr ""

#: nova/scheduler/driver.py:63
msgid "Exception during scheduler.run_instance"
msgstr ""

#: nova/scheduler/driver.py:67 nova/scheduler/manager.py:183
#, python-format
msgid "Setting instance to %(state)s state."
msgstr ""

#: nova/scheduler/driver.py:144
msgid "Driver must implement schedule_prep_resize"
msgstr ""

#: nova/scheduler/driver.py:152
msgid "Driver must implement schedule_run_instance"
msgstr ""

#: nova/scheduler/driver.py:284
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""

#: nova/scheduler/filter_scheduler.py:52
#, python-format
msgid "Attempting to build %(num_instances)d instance(s)"
msgstr ""

#: nova/scheduler/filter_scheduler.py:189
msgid "Invalid value for 'scheduler_max_attempts', must be >= 1"
msgstr ""

#: nova/scheduler/filter_scheduler.py:216
#, python-format
msgid ""
"Exceeded max scheduling attempts %(max_attempts)d for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/scheduler/filter_scheduler.py:270
#, python-format
msgid "Filtered %(hosts)s"
msgstr ""

#: nova/scheduler/filter_scheduler.py:275
#, python-format
msgid "Choosing host %(best_host)s"
msgstr ""

#: nova/scheduler/host_manager.py:304
#, python-format
msgid "Host filter ignoring hosts: %(ignored_hosts)s"
msgstr ""

#: nova/scheduler/host_manager.py:313
#, python-format
msgid ""
"No hosts matched due to not matching 'force_hosts'value of "
"'%(forced_hosts)s'"
msgstr ""

#: nova/scheduler/host_manager.py:318
#, python-format
msgid "Host filter forcing available hosts to %(forced_hosts)s"
msgstr ""

#: nova/scheduler/host_manager.py:334
#, python-format
msgid "Ignoring %(service_name)s service update from %(host)s"
msgstr ""

#: nova/scheduler/host_manager.py:339
#, python-format
msgid "Received %(service_name)s service update from %(state_key)s."
msgstr ""

#: nova/scheduler/host_manager.py:357
#, python-format
msgid "No service for compute ID %s"
msgstr ""

#: nova/scheduler/manager.py:167
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: nova/scheduler/scheduler_options.py:68
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: nova/scheduler/scheduler_options.py:77
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: nova/scheduler/filters/__init__.py:55
msgid ""
"Use 'nova.scheduler.filters.all_filters' instead of "
"'nova.scheduler.filters.standard_filters'"
msgstr ""

#: nova/scheduler/filters/aggregate_instance_extra_specs.py:49
#: nova/scheduler/filters/aggregate_instance_extra_specs.py:56
#: nova/scheduler/filters/compute_capabilities_filter.py:57
#, python-format
msgid "%(host_state)s fails instance_type extra_specs requirements"
msgstr ""

#: nova/scheduler/filters/compute_filter.py:40
#, python-format
msgid "%(host_state)s is disabled or has not been heard from in a while"
msgstr ""

#: nova/scheduler/filters/compute_filter.py:44
#, python-format
msgid "%(host_state)s is disabled via capabilities"
msgstr ""

#: nova/scheduler/filters/core_filter.py:44
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: nova/scheduler/filters/disk_filter.py:46
#, python-format
msgid ""
"%(host_state)s does not have %(requested_disk)s MB usable disk, it only "
"has %(usable_disk_mb)s MB usable disk."
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:48
#, python-format
msgid ""
"Instance contains properties %(image_props)s, but no corresponding "
"capabilities are advertised by the compute node"
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:61
#, python-format
msgid ""
"Instance properties %(image_props)s are satisfied by compute host "
"capabilities %(capabilities)s"
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:66
#, python-format
msgid ""
"Instance contains properties %(image_props)s that are not provided by the"
" compute node capabilities %(capabilities)s"
msgstr ""

#: nova/scheduler/filters/image_props_filter.py:82
#, python-format
msgid "%(host_state)s does not support requested instance_properties"
msgstr ""

#: nova/scheduler/filters/io_ops_filter.py:41
#, python-format
msgid ""
"%(host_state)s fails I/O ops check: Max IOs per host is set to "
"%(max_io_ops)s"
msgstr ""

#: nova/scheduler/filters/num_instances_filter.py:38
#, python-format
msgid ""
"%(host_state)s fails num_instances check: Max instances per host is set "
"to %(max_instances)s"
msgstr ""

#: nova/scheduler/filters/ram_filter.py:45
#, python-format
msgid ""
"%(host_state)s does not have %(requested_ram)s MB usable ram, it only has"
" %(usable_ram)s MB usable ram."
msgstr ""

#: nova/scheduler/filters/retry_filter.py:38
#, python-format
msgid "Previously tried hosts: %(hosts)s.  (host=%(host)s)"
msgstr ""

#: nova/scheduler/filters/trusted_filter.py:200
#, python-format
msgid "TCP: trust state of %(host)s:%(level)s(%(trust)s)"
msgstr ""

#: nova/scheduler/weights/__init__.py:58
msgid "least_cost has been deprecated in favor of the RAM Weigher."
msgstr ""

#: nova/servicegroup/api.py:48
#, python-format
msgid "ServiceGroup driver defined as an instance of %s"
msgstr ""

#: nova/servicegroup/api.py:54
#, python-format
msgid "unknown ServiceGroup driver name: %s"
msgstr ""

#: nova/servicegroup/api.py:70
#, python-format
msgid ""
"Join new ServiceGroup member %(member_id)s to the %(group_id)s group, "
"service = %(service)s"
msgstr ""

#: nova/servicegroup/api.py:77
#, python-format
msgid "Check if the given member [%s] is part of the ServiceGroup, is up"
msgstr ""

#: nova/servicegroup/api.py:86
#, python-format
msgid ""
"Explicitly remove the given member %(member_id)s from the%(group_id)s "
"group monitoring"
msgstr ""

#: nova/servicegroup/api.py:93
#, python-format
msgid "Returns ALL members of the [%s] ServiceGroup"
msgstr ""

#: nova/servicegroup/api.py:101
#, python-format
msgid "Returns one member of the [%s] group"
msgstr ""

#: nova/servicegroup/db_driver.py:36
#, python-format
msgid ""
"DB_Driver: join new ServiceGroup member %(member_id)s to the %(group_id)s"
" group, service = %(service)s"
msgstr ""

#: nova/servicegroup/db_driver.py:40
msgid "service is a mandatory argument for DB based ServiceGroup driver"
msgstr ""

#: nova/servicegroup/db_driver.py:64
#, python-format
msgid "DB_Driver: get_all members of the %s group"
msgstr ""

#: nova/servicegroup/db_driver.py:81
msgid "The service database object disappeared, Recreating it."
msgstr ""

#: nova/servicegroup/db_driver.py:96
msgid "Recovered model server connection!"
msgstr ""

#: nova/servicegroup/db_driver.py:102
msgid "model server went away"
msgstr ""

#: nova/tests/fake_ldap.py:34
msgid "Attempted to instantiate singleton"
msgstr ""

#: nova/tests/fake_utils.py:72
#, python-format
msgid "Faking execution of cmd (subprocess): %s"
msgstr ""

#: nova/tests/fake_utils.py:80
#, python-format
msgid "Faked command matched %s"
msgstr ""

#: nova/tests/fake_utils.py:96
#, python-format
msgid "Faked command raised an exception %s"
msgstr ""

#: nova/tests/fake_utils.py:101
#, python-format
msgid "Reply to faked command is stdout='%(stdout)s' stderr='%(stderr)s'"
msgstr ""

#: nova/tests/fake_volume.py:182 nova/volume/cinder.py:158
msgid "status must be available"
msgstr ""

#: nova/tests/fake_volume.py:186 nova/volume/cinder.py:161
msgid "already attached"
msgstr ""

#: nova/tests/fake_volume.py:191 nova/volume/cinder.py:167
msgid "already detached"
msgstr ""

#: nova/tests/fakelibvirt.py:849
msgid "Please extend mock libvirt module to support flags"
msgstr ""

#: nova/tests/fakelibvirt.py:853
msgid "Expected a list for 'auth' parameter"
msgstr ""

#: nova/tests/fakelibvirt.py:857
msgid "Expected a function in 'auth[0]' parameter"
msgstr ""

#: nova/tests/fakelibvirt.py:861
msgid "Expected a function in 'auth[1]' parameter"
msgstr ""

#: nova/tests/test_misc.py:62
#, python-format
msgid ""
"The following migrations are missing a downgrade:\n"
"\t%s"
msgstr ""

#: nova/tests/test_nova_manage.py:202
msgid "id"
msgstr ""

#: nova/tests/test_nova_manage.py:203
msgid "IPv4"
msgstr ""

#: nova/tests/test_nova_manage.py:204
msgid "IPv6"
msgstr ""

#: nova/tests/test_nova_manage.py:205
msgid "start address"
msgstr ""

#: nova/tests/test_nova_manage.py:206
msgid "DNS1"
msgstr ""

#: nova/tests/test_nova_manage.py:207
msgid "DNS2"
msgstr ""

#: nova/tests/test_nova_manage.py:208
msgid "VlanID"
msgstr ""

#: nova/tests/test_nova_manage.py:209
msgid "project"
msgstr ""

#: nova/tests/test_nova_manage.py:210
msgid "uuid"
msgstr ""

#: nova/tests/test_xenapi.py:731
#, python-format
msgid "Creating files in %s to simulate guest agent"
msgstr ""

#: nova/tests/test_xenapi.py:742
#, python-format
msgid "Removing simulated guest agent files in %s"
msgstr ""

#: nova/tests/api/test_auth.py:79
msgid "200 Role Match"
msgstr ""

#: nova/tests/api/test_auth.py:81
msgid "200 No Roles"
msgstr ""

#: nova/tests/api/test_auth.py:84
msgid "unexpected role header"
msgstr ""

#: nova/tests/api/openstack/compute/test_servers.py:3016
msgid ""
"Quota exceeded for instances: Requested 1, but already used 10 of 10 "
"instances"
msgstr ""

#: nova/tests/api/openstack/compute/test_servers.py:3021
msgid "Quota exceeded for ram: Requested 4096, but already used 8192 of 10240 ram"
msgstr ""

#: nova/tests/api/openstack/compute/test_servers.py:3026
msgid "Quota exceeded for cores: Requested 2, but already used 9 of 10 cores"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:53
#, python-format
msgid "_create: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:62
#, python-format
msgid "_delete: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:71
#, python-format
msgid "_get: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:81
#, python-format
msgid "_get_all: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:125
#, python-format
msgid "test_snapshot_create: param=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:134
#, python-format
msgid "test_snapshot_create: resp_dict=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:156
#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:182
#, python-format
msgid "test_snapshot_create_force: param=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:165
#, python-format
msgid "test_snapshot_create_force: resp_dict=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:218
#, python-format
msgid "test_snapshot_show: resp=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:244
#, python-format
msgid "test_snapshot_detail: resp_dict=%s"
msgstr ""

#: nova/tests/compute/test_compute.py:638
#: nova/tests/compute/test_compute.py:656
#: nova/tests/compute/test_compute.py:692
#: nova/tests/compute/test_compute.py:717
#: nova/tests/compute/test_compute.py:2462
#, python-format
msgid "Running instances: %s"
msgstr ""

#: nova/tests/compute/test_compute.py:644
#: nova/tests/compute/test_compute.py:679
#: nova/tests/compute/test_compute.py:705
#: nova/tests/compute/test_compute.py:735
#, python-format
msgid "After terminating instances: %s"
msgstr ""

#: nova/tests/compute/test_compute.py:1114
msgid "Internal error"
msgstr ""

#: nova/tests/compute/test_compute.py:2473
#, python-format
msgid "After force-killing instances: %s"
msgstr ""

#: nova/tests/hyperv/hypervutils.py:141 nova/virt/hyperv/vmops.py:555
#, python-format
msgid "Failed to change vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: nova/tests/hyperv/hypervutils.py:199 nova/virt/hyperv/vmops.py:490
#, python-format
msgid "Failed to destroy vm %s"
msgstr ""

#: nova/tests/hyperv/hypervutils.py:242 nova/virt/hyperv/snapshotops.py:92
#, python-format
msgid "Failed to get info for disk %s"
msgstr ""

#: nova/tests/hyperv/mockproxy.py:74
#, python-format
msgid "Couldn't find invocation num. %(c)d of attribute \"%(name)s\""
msgstr ""

#: nova/tests/hyperv/mockproxy.py:93 nova/tests/hyperv/mockproxy.py:121
#, python-format
msgid "Couldn't find attribute \"%s\""
msgstr ""

#: nova/tests/hyperv/mockproxy.py:98
#, python-format
msgid "Couldn't find attribute \"%(name)s\" with arguments \"%(params)s\""
msgstr ""

#: nova/tests/hyperv/mockproxy.py:101
#, python-format
msgid ""
"Couldn't find invocation num. %(c)d of attribute \"%(name)s\" with "
"arguments \"%(params)s\""
msgstr ""

#: nova/tests/integrated/test_api_samples.py:143
#, python-format
msgid "Result: %(result)s is not a dict."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:147
#, python-format
msgid ""
"Key mismatch:\n"
"%(ex_keys)s\n"
"%(res_keys)s"
msgstr ""

#: nova/tests/integrated/test_api_samples.py:155
#, python-format
msgid "Result: %(result)s is not a list."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:158
#, python-format
msgid ""
"Length mismatch: %(result)s\n"
"%(expected)s."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:169
#, python-format
msgid "Result: %(res_obj)s not in %(expected)s."
msgstr ""

#: nova/tests/integrated/test_api_samples.py:187
#: nova/tests/integrated/test_api_samples.py:200
#, python-format
msgid ""
"Values do not match:\n"
"%(expected)s\n"
"%(result)s"
msgstr ""

#: nova/tests/integrated/test_login.py:31
#, python-format
msgid "flavor: %s"
msgstr ""

#: nova/tests/integrated/api/client.py:38
#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""

#: nova/tests/integrated/api/client.py:47
msgid "Authentication error"
msgstr ""

#: nova/tests/integrated/api/client.py:55
msgid "Authorization error"
msgstr ""

#: nova/tests/integrated/api/client.py:63
msgid "Item not found"
msgstr ""

#: nova/tests/integrated/api/client.py:105
#, python-format
msgid "Doing %(method)s on %(relative_url)s"
msgstr ""

#: nova/tests/integrated/api/client.py:107
#, python-format
msgid "Body: %s"
msgstr ""

#: nova/tests/integrated/api/client.py:125
#, python-format
msgid "%(auth_uri)s => code %(http_status)s"
msgstr ""

#: nova/tests/integrated/api/client.py:155
#, python-format
msgid "%(relative_uri)s => code %(http_status)s"
msgstr ""

#: nova/tests/integrated/api/client.py:165
msgid "Unexpected status code"
msgstr ""

#: nova/tests/integrated/api/client.py:172
#, python-format
msgid "Decoding JSON: %s"
msgstr ""

#: nova/virt/configdrive.py:80
#, python-format
msgid "Added %(filepath)s to config drive"
msgstr ""

#: nova/virt/driver.py:789
msgid "Compute driver option required, but not specified"
msgstr ""

#: nova/virt/driver.py:792
#, python-format
msgid "Loading compute driver '%s'"
msgstr ""

#: nova/virt/driver.py:799
#, python-format
msgid "Unable to load the virtualization driver: %s"
msgstr ""

#: nova/virt/fake.py:198
#, python-format
msgid "Key '%(key)s' not in instances '%(inst)s'"
msgstr ""

#: nova/virt/firewall.py:179 nova/virt/libvirt/firewall.py:251
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: nova/virt/firewall.py:190
msgid "Filters added to instance"
msgstr ""

#: nova/virt/firewall.py:192
msgid "Provider Firewall Rules refreshed"
msgstr ""

#: nova/virt/firewall.py:360
#, python-format
msgid "Adding security group rule: %r"
msgstr ""

#: nova/virt/firewall.py:491 nova/virt/xenapi/firewall.py:75
#, python-format
msgid "Adding provider rule: %s"
msgstr ""

#: nova/virt/images.py:113
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: nova/virt/images.py:212
msgid "'qemu-img info' parsing failed."
msgstr ""

#: nova/virt/images.py:218
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: nova/virt/images.py:229
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: nova/virt/baremetal/db/sqlalchemy/api.py:260
msgid "No more PXE IPs available"
msgstr ""

#: nova/virt/baremetal/db/sqlalchemy/api.py:282
#: nova/virt/baremetal/db/sqlalchemy/api.py:323
#, python-format
msgid "Baremetal interface %s not found"
msgstr ""

#: nova/virt/baremetal/db/sqlalchemy/api.py:333
#, python-format
msgid "Baremetal interface %s already in use"
msgstr ""

#: nova/virt/baremetal/db/sqlalchemy/api.py:347
#, python-format
msgid "Baremetal virtual interface %s not found"
msgstr ""

#: nova/virt/disk/api.py:220
msgid "image already mounted"
msgstr ""

#: nova/virt/disk/api.py:266
#, python-format
msgid ""
"Inject data image=%(image)s key=%(key)s net=%(net)s metadata=%(metadata)s"
" admin_password=ha-ha-not-telling-you files=%(files)s "
"partition=%(partition)s use_cow=%(use_cow)s"
msgstr ""

#: nova/virt/disk/api.py:290
#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': "
"%(errors)s"
msgstr ""

#: nova/virt/disk/api.py:307
#, python-format
msgid "Failed to unmount container filesystem: %s"
msgstr ""

#: nova/virt/disk/api.py:329
#, python-format
msgid "Inject file fs=%(fs)s path=%(path)s append=%(append)s"
msgstr ""

#: nova/virt/disk/api.py:338
#, python-format
msgid "Inject metadata fs=%(fs)s metadata=%(metadata)s"
msgstr ""

#: nova/virt/disk/api.py:376
#, python-format
msgid "Inject key fs=%(fs)s key=%(key)s"
msgstr ""

#: nova/virt/disk/api.py:404
#, python-format
msgid "Inject key fs=%(fs)s net=%(net)s"
msgstr ""

#: nova/virt/disk/api.py:430
#, python-format
msgid "Inject admin password fs=%(fs)s admin_passwd=ha-ha-not-telling-you"
msgstr ""

#: nova/virt/disk/api.py:475
msgid "Not implemented on Windows"
msgstr ""

#: nova/virt/disk/api.py:504
#, python-format
msgid "User %(username)s not found in password file."
msgstr ""

#: nova/virt/disk/api.py:520
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr ""

#: nova/virt/disk/mount/api.py:38
#, python-format
msgid ""
"Instance for format imgfile=%(imgfile)s mountdir=%(mountdir)s "
"partition=%(partition)s imgfmt=%(imgfmt)s"
msgstr ""

#: nova/virt/disk/mount/api.py:42 nova/virt/disk/mount/api.py:58
#: nova/virt/disk/vfs/localfs.py:67
msgid "Using LoopMount"
msgstr ""

#: nova/virt/disk/mount/api.py:47 nova/virt/disk/mount/api.py:63
#: nova/virt/disk/vfs/localfs.py:72
msgid "Using NbdMount"
msgstr ""

#: nova/virt/disk/mount/api.py:54
#, python-format
msgid ""
"Instance for device imgfile=%(imgfile)s mountdir=%(mountdir)s "
"partition=%(partition)s device=%(device)s"
msgstr ""

#: nova/virt/disk/mount/api.py:112
#, python-format
msgid "Map dev %s"
msgstr ""

#: nova/virt/disk/mount/api.py:117
#, python-format
msgid "partition search unsupported with %s"
msgstr ""

#: nova/virt/disk/mount/api.py:133
#, python-format
msgid "partition %s not found"
msgstr ""

#: nova/virt/disk/mount/api.py:134
#, python-format
msgid "Failed to map partitions: %s"
msgstr ""

#: nova/virt/disk/mount/api.py:156
#, python-format
msgid "Unmap dev %s"
msgstr ""

#: nova/virt/disk/mount/api.py:164
#, python-format
msgid "Mount %(dev)s on %(dir)s"
msgstr ""

#: nova/virt/disk/mount/api.py:169
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: nova/virt/disk/mount/api.py:179
#, python-format
msgid "Umount %s"
msgstr ""

#: nova/virt/disk/mount/api.py:190
msgid "Fail to mount, tearing back down"
msgstr ""

#: nova/virt/disk/mount/loop.py:33
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: nova/virt/disk/mount/loop.py:37
#, python-format
msgid "Got loop device %s"
msgstr ""

#: nova/virt/disk/mount/loop.py:44
#, python-format
msgid "Release loop device %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:59
msgid "nbd unavailable: module not loaded"
msgstr ""

#: nova/virt/disk/mount/nbd.py:64
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/mount/nbd.py:83
#, python-format
msgid "Get nbd device %(dev)s for %(imgfile)s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:88
#, python-format
msgid "qemu-nbd error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:100
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: nova/virt/disk/mount/nbd.py:110
#, python-format
msgid "Release nbd device %s"
msgstr ""

#: nova/virt/disk/vfs/api.py:27
#, python-format
msgid ""
"Instance for image imgfile=%(imgfile)s imgfmt=%(imgfmt)s "
"partition=%(partition)s"
msgstr ""

#: nova/virt/disk/vfs/api.py:32
msgid "Trying to import guestfs"
msgstr ""

#: nova/virt/disk/vfs/api.py:39
msgid "Using primary VFSGuestFS"
msgstr ""

#: nova/virt/disk/vfs/api.py:44
msgid "Falling back to VFSLocalFS"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:52
#, python-format
msgid "Mount guest OS image %(imgfile)s partition %(part)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:61
#, python-format
msgid "Inspecting guest OS image %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:65
#, python-format
msgid "No operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:69
#, python-format
msgid "Multi-boot OS %(roots)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:71
#, python-format
msgid "Multi-boot operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:77
#, python-format
msgid "Inspecting guest OS root filesystem %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:82
#, python-format
msgid "No mount points found in %(root)s of %(imgfile)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:87
#, python-format
msgid "Mounting %(dev)s at %(dir)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:93
#, python-format
msgid "Setting up appliance for %(imgfile)s %(imgfmt)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:108
msgid "Tearing down appliance"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:112
#, python-format
msgid "Failed to close augeas %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:116
#, python-format
msgid "Failed to shutdown appliance %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:120
#, python-format
msgid "Failed to close guest handle %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:130 nova/virt/disk/vfs/localfs.py:103
#, python-format
msgid "Make directory path=%(path)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:135 nova/virt/disk/vfs/localfs.py:108
#, python-format
msgid "Append file path=%(path)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:140 nova/virt/disk/vfs/localfs.py:117
#, python-format
msgid "Replace file path=%(path)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:145 nova/virt/disk/vfs/localfs.py:126
#, python-format
msgid "Read file path=%(path)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:150 nova/virt/disk/vfs/localfs.py:132
#, python-format
msgid "Has file path=%(path)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:159
#, python-format
msgid "Set permissions path=%(path)s mode=%(mode)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:164
#, python-format
msgid "Set ownership path=%(path)s user=%(user)s group=%(group)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:177
#, python-format
msgid "chown uid=%(uid)d gid=%(gid)s"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:46
#, python-format
msgid "File path %s not valid"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:77
#, python-format
msgid "Failed to mount image: %s"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:81
#, python-format
msgid "Failed to mount image %(ex)s)"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:91
#, python-format
msgid "Failed to unmount %(imgdir)s: %(ex)s"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:97
#, python-format
msgid "Failed to remove %(imgdir)s: %(ex)s"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:140
#, python-format
msgid "Set permissions path=%(path)s mode=%(mode)o"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:145
#, python-format
msgid "Set permissions path=%(path)s user=%(user)s group=%(group)s"
msgstr ""

#: nova/virt/hyperv/driver.py:190 nova/virt/hyperv/driver.py:193
msgid "plug_vifs called"
msgstr ""

#: nova/virt/hyperv/driver.py:196
msgid "ensure_filtering_rules_for_instance called"
msgstr ""

#: nova/virt/hyperv/driver.py:201
msgid "unfilter_instance called"
msgstr ""

#: nova/virt/hyperv/driver.py:205
msgid "confirm_migration called"
msgstr ""

#: nova/virt/hyperv/driver.py:210
msgid "finish_revert_migration called"
msgstr ""

#: nova/virt/hyperv/driver.py:216
msgid "finish_migration called"
msgstr ""

#: nova/virt/hyperv/driver.py:219
msgid "get_console_output called"
msgstr ""

#: nova/virt/hyperv/hostops.py:78 nova/virt/libvirt/driver.py:2010
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. This error can be safely ignored for now."
msgstr ""

#: nova/virt/hyperv/hostops.py:134
#, python-format
msgid "Windows version: %s "
msgstr ""

#: nova/virt/hyperv/hostops.py:146
msgid "get_available_resource called"
msgstr ""

#: nova/virt/hyperv/hostops.py:163 nova/virt/libvirt/driver.py:3058
#: nova/virt/xenapi/host.py:150
msgid "Updating host stats"
msgstr ""

#: nova/virt/hyperv/hostops.py:183
msgid "get_host_stats called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:53
msgid ""
"Live migration is not supported \"                     \"by this version "
"of Hyper-V"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:62
msgid "Live migration is not enabled on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:65
msgid "Live migration networks are not configured on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:69
msgid "live_migration called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:95
#, python-format
msgid "Getting live migration networks for remote host: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:114
#, python-format
msgid "Starting live migration for instance: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:127
#, python-format
msgid "Failed to live migrate VM %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:130
#, python-format
msgid "Calling live migration recover_method for instance: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:134
#, python-format
msgid "Calling live migration post_method for instance: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:140
msgid "pre_live_migration called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:158
msgid "post_live_migration_at_destination called"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:162
#, python-format
msgid "compare_cpu called %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:57
#, python-format
msgid "Creating snapshot for instance %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:71
#, python-format
msgid "Failed to create snapshot for VM %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:83
#, python-format
msgid "Getting info for VHD %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:106
#, python-format
msgid "Copying VHD %(src_vhd_path)s to %(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:116
#, python-format
msgid "Copying base disk %(src_vhd_path)s to %(dest_base_disk_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:120
#, python-format
msgid ""
"Reconnecting copied base VHD %(dest_base_disk_path)s and diff VHD "
"%(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:134
#, python-format
msgid ""
"Failed to reconnect base disk %(dest_base_disk_path)s and diff disk "
"%(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:139
#, python-format
msgid "Merging base disk %(dest_base_disk_path)s and diff disk %(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:151
#, python-format
msgid ""
"Failed to merge base disk %(dest_base_disk_path)s and diff disk "
"%(dest_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:164
#, python-format
msgid ""
"Updating Glance image %(image_id)s with content from merged disk "
"%(image_vhd_path)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:169
#, python-format
msgid "Snapshot image %(image_id)s updated for VM %(instance_name)s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:172
#, python-format
msgid "Removing snapshot %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:181
#, python-format
msgid "Failed to remove snapshot for VM %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:186
#, python-format
msgid "Removing folder %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:80
msgid "get_info called for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:104
#, python-format
msgid "hyperv vm state: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:110
#, python-format
msgid ""
"Got Info for vm %(instance_name)s: state=%(state)d, mem=%(memusage)s, "
"num_cpu=%(numprocs)s, uptime=%(uptime)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:146
#, python-format
msgid "cache image failed: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:170
#, python-format
msgid "Starting VM %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:172
#, python-format
msgid "Started VM %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:174
#, python-format
msgid "spawn vm failed: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:180
#, python-format
msgid "Invalid config_drive_format \"%s\""
msgstr ""

#: nova/virt/hyperv/vmops.py:183 nova/virt/libvirt/driver.py:1427
msgid "Using config drive"
msgstr ""

#: nova/virt/hyperv/vmops.py:194 nova/virt/libvirt/driver.py:1437
#, python-format
msgid "Creating config drive at %(path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:239
#, python-format
msgid "Failed to create VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:242
#, python-format
msgid "Created VM %s..."
msgstr ""

#: nova/virt/hyperv/vmops.py:259
#, python-format
msgid "Set memory for vm %s..."
msgstr ""

#: nova/virt/hyperv/vmops.py:272
#, python-format
msgid "Set vcpus for vm %s..."
msgstr ""

#: nova/virt/hyperv/vmops.py:276
#, python-format
msgid "Creating a scsi controller for %(vm_name)s for volume attaching"
msgstr ""

#: nova/virt/hyperv/vmops.py:285
msgid "Controller not found"
msgstr ""

#: nova/virt/hyperv/vmops.py:293
#, python-format
msgid "Failed to add scsi controller to VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:310
#, python-format
msgid "Creating disk for %(vm_name)s by attaching disk file %(path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:338
#, python-format
msgid "Failed to add drive to VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:341
#, python-format
msgid "New %(drive_type)s drive path is %(drive_path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:366
#, python-format
msgid "Failed to add %(drive_type)s image to VM %(vm_name)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:368
#, python-format
msgid "Created drive type %(drive_type)s for %(vm_name)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:373
#, python-format
msgid "Creating nic for %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:378
msgid "Cannot find vSwitch"
msgstr ""

#: nova/virt/hyperv/vmops.py:398
msgid "Failed creating a port on the external vswitch"
msgstr ""

#: nova/virt/hyperv/vmops.py:399
#, python-format
msgid "Failed creating port for %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:402
#, python-format
msgid "Created switch port %(vm_name)s on switch %(ext_path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:414
#, python-format
msgid "Failed to add nic to VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:416
#, python-format
msgid "Created nic for %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:423 nova/virt/hyperv/vmops.py:426
#, python-format
msgid "Attempting to bind NIC to %s "
msgstr ""

#: nova/virt/hyperv/vmops.py:431
msgid "No vSwitch specified, attaching to default"
msgstr ""

#: nova/virt/hyperv/vmops.py:456
#, python-format
msgid "Got request to destroy vm %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:500
#, python-format
msgid "Del: disk %(vhdfile)s vm %(instance_name)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:506
msgid "Pause instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:511
msgid "Unpause instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:517
msgid "Suspend instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:522
msgid "Resume instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:527
msgid "Power off instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:532
msgid "Power on instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:552
#, python-format
msgid "Successfully changed vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:581
#, python-format
msgid "use_cow_image:%s"
msgstr ""

#: nova/virt/hyperv/vmops.py:601
#, python-format
msgid "Failed to create Difference Disk from %(base)s to %(target)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:54
#, python-format
msgid "duplicate name found: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:72
#, python-format
msgid ""
"WMI job failed with status %(job_state)d. Error details: %(err_sum_desc)s"
" - %(err_desc)s - Error code: %(err_code)d"
msgstr ""

#: nova/virt/hyperv/vmutils.py:78
#, python-format
msgid "WMI job failed with status %(job_state)d. Error details: %(error)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:81
#, python-format
msgid "WMI job failed with status %(job_state)d. No error description available"
msgstr ""

#: nova/virt/hyperv/vmutils.py:86
#, python-format
msgid "WMI job succeeded: %(desc)s, Elapsed=%(elap)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:93 nova/virt/hyperv/vmutils.py:113
#, python-format
msgid "Creating folder %s "
msgstr ""

#: nova/virt/hyperv/vmutils.py:111
#, python-format
msgid "Removing existing folder %s "
msgstr ""

#: nova/virt/hyperv/volumeops.py:69 nova/virt/xenapi/vm_utils.py:512
#, python-format
msgid "block device info: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:97
#, python-format
msgid "Attach boot from volume failed: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:100
#, python-format
msgid "Unable to attach boot volume to instance %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:109 nova/virt/xenapi/volumeops.py:114
#, python-format
msgid "Attach_volume: %(connection_info)s, %(instance_name)s, %(mountpoint)s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:134
#, python-format
msgid "Attach volume failed: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:137 nova/virt/xenapi/volumeops.py:199
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:156
#, python-format
msgid "Failed to add volume to VM %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:170
#, python-format
msgid "Detach_volume: %(connection_info)s, %(instance_name)s, %(mountpoint)s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:187
#, python-format
msgid "Mounted disk to detach is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:188
#, python-format
msgid "host_resource disk detached is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:191
#, python-format
msgid "Physical disk detached is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:198
#, python-format
msgid "Failed to remove volume from VM %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:207 nova/virt/libvirt/driver.py:610
msgid "Could not determine iscsi initiator name"
msgstr ""

#: nova/virt/hyperv/volumeops.py:224
#, python-format
msgid "device.InitiatorName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:225
#, python-format
msgid "device.TargetName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:226
#, python-format
msgid "device.ScsiPortNumber: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:227
#, python-format
msgid "device.ScsiPathId: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:228
#, python-format
msgid "device.ScsiTargetId): %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:229
#, python-format
msgid "device.ScsiLun: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:230
#, python-format
msgid "device.DeviceInterfaceGuid :%s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:232
#, python-format
msgid "device.DeviceInterfaceName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:234
#, python-format
msgid "device.LegacyName: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:235
#, python-format
msgid "device.DeviceType: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:236
#, python-format
msgid "device.DeviceNumber %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:237
#, python-format
msgid "device.PartitionNumber :%s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:243 nova/virt/hyperv/volumeops.py:262
#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:245
#, python-format
msgid "Device number : %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:246
#, python-format
msgid "Target lun : %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:252 nova/virt/hyperv/volumeops.py:259
#, python-format
msgid "Mounted disk is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:276
#, python-format
msgid "Drive number to disconnect is: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:283
#, python-format
msgid "DeviceNumber : %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:288
#, python-format
msgid "Disk path to parse: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:290
#, python-format
msgid "start_device_id: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:292
#, python-format
msgid "end_device_id: %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:52
#, python-format
msgid "An error has occurred when calling the iscsi initiator: %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:69
msgid "The ISCSI initiator name can't be found. Choosing the default one"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:122 nova/virt/libvirt/driver.py:1488
#: nova/virt/xenapi/vm_utils.py:505
#, python-format
msgid "block_device_list %s"
msgstr ""

#: nova/virt/libvirt/driver.py:339
#, python-format
msgid "Nova requires libvirt version %(major)i.%(minor)i.%(micro)i or greater."
msgstr ""

#: nova/virt/libvirt/driver.py:345
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:366
msgid "Connection to libvirt broke"
msgstr ""

#: nova/virt/libvirt/driver.py:388 nova/virt/libvirt/driver.py:391
#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr ""

#: nova/virt/libvirt/driver.py:473
#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:487
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:492
msgid "Instance destroyed successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:514
msgid "Error from libvirt during undefineFlags. Retrying with undefine"
msgstr ""

#: nova/virt/libvirt/driver.py:529
#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:542
#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:559
#, python-format
msgid "Deleting instance files %(target)s"
msgstr ""

#: nova/virt/libvirt/driver.py:573
#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:733
msgid "During detach_volume, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:743
msgid "attaching LXC block device"
msgstr ""

#: nova/virt/libvirt/driver.py:763
msgid "detaching LXC block device"
msgstr ""

#: nova/virt/libvirt/driver.py:895
msgid "Instance soft rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:899
msgid "Failed to soft reboot instance."
msgstr ""

#: nova/virt/libvirt/driver.py:931
msgid "Instance shutdown successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:967
msgid "Instance rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:1099
msgid "Instance is running"
msgstr ""

#: nova/virt/libvirt/driver.py:1106 nova/virt/powervm/operator.py:256
msgid "Instance spawned successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:1122
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: nova/virt/libvirt/driver.py:1160 nova/virt/libvirt/driver.py:1186
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr ""

#: nova/virt/libvirt/driver.py:1175
msgid "Guest does not have a console available"
msgstr ""

#: nova/virt/libvirt/driver.py:1224
#, python-format
msgid "Path '%(path)s' supports direct I/O"
msgstr ""

#: nova/virt/libvirt/driver.py:1228
#, python-format
msgid "Path '%(path)s' does not support direct I/O: '%(ex)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:1232 nova/virt/libvirt/driver.py:1236
#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:1302
msgid "Creating image"
msgstr ""

#: nova/virt/libvirt/driver.py:1451
#, python-format
msgid "Injecting %(injection)s into image %(img_id)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1461
#, python-format
msgid "Ignoring error injecting data into image %(img_id)s (%(e)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:1535
#, python-format
msgid ""
"Config requested an explicit CPU model, but the current libvirt "
"hypervisor '%s' does not support selecting CPU models"
msgstr ""

#: nova/virt/libvirt/driver.py:1541
msgid "Config requested a custom CPU model, but no model name was provided"
msgstr ""

#: nova/virt/libvirt/driver.py:1545
msgid "A CPU model name should not be set when a host CPU model is requested"
msgstr ""

#: nova/virt/libvirt/driver.py:1549
#, python-format
msgid "CPU mode '%(mode)s' model '%(model)s' was chosen"
msgstr ""

#: nova/virt/libvirt/driver.py:1565
msgid ""
"Passthrough of the host CPU was requested but this libvirt version does "
"not support this feature"
msgstr ""

#: nova/virt/libvirt/driver.py:1855
msgid "Starting toXML method"
msgstr ""

#: nova/virt/libvirt/driver.py:1859
msgid "Finished toXML method"
msgstr ""

#: nova/virt/libvirt/driver.py:1876
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2128
msgid "libvirt version is too old (does not support getVersion)"
msgstr ""

#: nova/virt/libvirt/driver.py:2316
msgid "Block migration can not be used with shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:2324
msgid "Live migration can not be used without shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:2359
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too "
"large(available on destination host:%(available)s < need:%(necessary)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:2384
#, python-format
msgid ""
"Instance launched has CPU info:\n"
"%s"
msgstr ""

#: nova/virt/libvirt/driver.py:2396
#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2413
#, python-format
msgid ""
"Creating tmpfile %s to notify to other compute nodes that they should "
"mount the same storage."
msgstr ""

#: nova/virt/libvirt/driver.py:2461
#, python-format
msgid "The firewall filter for %s does not exist"
msgstr ""

#: nova/virt/libvirt/driver.py:2531
#, python-format
msgid "Live Migration failure: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2575
#, python-format
msgid "plug_vifs() failed %(cnt)d.Retry up to %(max_retry)d for %(hostname)s."
msgstr ""

#: nova/virt/libvirt/driver.py:2702
#, python-format
msgid "skipping %(path)s since it looks like volume"
msgstr ""

#: nova/virt/libvirt/driver.py:2751
#, python-format
msgid "Getting disk size of %(i_name)s: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2813
msgid "Starting migrate_disk_and_power_off"
msgstr ""

#: nova/virt/libvirt/driver.py:2872
msgid "Instance running successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2879
msgid "Starting finish_migration"
msgstr ""

#: nova/virt/libvirt/driver.py:2930
msgid "Starting finish_revert_migration"
msgstr ""

#: nova/virt/libvirt/firewall.py:35
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: nova/virt/libvirt/firewall.py:104
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: nova/virt/libvirt/firewall.py:112
msgid "Ensuring static filters"
msgstr ""

#: nova/virt/libvirt/firewall.py:193
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) is not found."
msgstr ""

#: nova/virt/libvirt/firewall.py:216
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) for%(name)s is not found."
msgstr ""

#: nova/virt/libvirt/firewall.py:232
msgid "iptables firewall: Setup Basic Filtering"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:213
msgid "You should specify libvirt_images_volume_group flag to use LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:276
#, python-format
msgid "Unknown image_type=%s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:111
#, python-format
msgid "Error reading image info file %(filename)s: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:151
#, python-format
msgid "Reading image info file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:173
#, python-format
msgid "Writing stored info to %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:294
#, python-format
msgid "%s is a valid instance name"
msgstr ""

#: nova/virt/libvirt/imagecache.py:297
#, python-format
msgid "%s has a disk file"
msgstr ""

#: nova/virt/libvirt/imagecache.py:299
#, python-format
msgid "Instance %(instance)s is backed by %(backing)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:312
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: nova/virt/libvirt/imagecache.py:388
#, python-format
msgid "image %(id)s at (%(base_file)s): image verification failed"
msgstr ""

#: nova/virt/libvirt/imagecache.py:398
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash "
"stored"
msgstr ""

#: nova/virt/libvirt/imagecache.py:407
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr ""

#: nova/virt/libvirt/imagecache.py:422
#, python-format
msgid "Cannot remove %(base_file)s, it does not exist"
msgstr ""

#: nova/virt/libvirt/imagecache.py:434
#, python-format
msgid "Base file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:437
#, python-format
msgid "Removing base file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:444
#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:455
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr ""

#: nova/virt/libvirt/imagecache.py:479
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""

#: nova/virt/libvirt/imagecache.py:491
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): warning -- an absent base file is in "
"use! instances: %(instance_list)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:503
#, python-format
msgid "image %(id)s at (%(base_file)s): image is not in use"
msgstr ""

#: nova/virt/libvirt/imagecache.py:510
#, python-format
msgid "image %(id)s at (%(base_file)s): image is in use"
msgstr ""

#: nova/virt/libvirt/imagecache.py:534
#, python-format
msgid "Skipping verification, no base directory at %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:538
msgid "Verify base images"
msgstr ""

#: nova/virt/libvirt/imagecache.py:545
#, python-format
msgid "Image id %(id)s yields fingerprint %(fingerprint)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:563
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:568
#, python-format
msgid "Active base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:571
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:575
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:583
msgid "Verification complete"
msgstr ""

#: nova/virt/libvirt/snapshots.py:83 nova/virt/libvirt/snapshots.py:86
#: nova/virt/libvirt/snapshots.py:89
msgid "LVM snapshots not implemented"
msgstr ""

#: nova/virt/libvirt/utils.py:114
#, python-format
msgid ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db "
"available, but %(size)db required by volume %(lv)s."
msgstr ""

#: nova/virt/libvirt/utils.py:123
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. "
"Virtual volume size is %(size)db, but free space on volume group is only "
"%(free_space)db."
msgstr ""

#: nova/virt/libvirt/utils.py:170
#, python-format
msgid "Path %s must be LVM logical volume"
msgstr ""

#: nova/virt/libvirt/utils.py:389
msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr ""

#: nova/virt/libvirt/vif.py:95
#, python-format
msgid "Ensuring vlan %(vlan)s and bridge %(bridge)s"
msgstr ""

#: nova/virt/libvirt/vif.py:105
#, python-format
msgid "Ensuring bridge %s"
msgstr ""

#: nova/virt/libvirt/vif.py:181 nova/virt/libvirt/vif.py:247
msgid "Failed while unplugging vif"
msgstr ""

#: nova/virt/libvirt/volume.py:188
#, python-format
msgid "iSCSI device not found at %s"
msgstr ""

#: nova/virt/libvirt/volume.py:191
#, python-format
msgid ""
"ISCSI volume not yet found at: %(mount_device)s. Will rescan & retry.  "
"Try number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:203
#, python-format
msgid "Found iSCSI node %(mount_device)s (after %(tries)s rescans)"
msgstr ""

#: nova/virt/libvirt/volume_nfs.py:81
#, python-format
msgid "%s is already mounted"
msgstr ""

#: nova/virt/powervm/common.py:54
msgid "Connection error connecting PowerVM manager"
msgstr ""

#: nova/virt/powervm/common.py:111
msgid "File transfer to PowerVM manager failed"
msgstr ""

#: nova/virt/powervm/exception.py:21
msgid "Connection to PowerVM manager failed"
msgstr ""

#: nova/virt/powervm/exception.py:25
msgid "File '%(file_path)' transfer to PowerVM manager failed"
msgstr ""

#: nova/virt/powervm/exception.py:29
#, python-format
msgid "LPAR instance '%(instance_name)s' could not be found"
msgstr ""

#: nova/virt/powervm/exception.py:33
#, python-format
msgid "LPAR instance '%(instance_name)s' creation failed"
msgstr ""

#: nova/virt/powervm/exception.py:37
msgid "No space left on any volume group"
msgstr ""

#: nova/virt/powervm/exception.py:45
#, python-format
msgid "Operation '%(operation)s' on LPAR '%(instance_name)s' timed out"
msgstr ""

#: nova/virt/powervm/exception.py:50
msgid "Image creation failed on PowerVM"
msgstr ""

#: nova/virt/powervm/exception.py:54
#, python-format
msgid ""
"Insufficient free memory on PowerVM system to spawn instance "
"'%(instance_name)s'"
msgstr ""

#: nova/virt/powervm/exception.py:59
#, python-format
msgid ""
"Insufficient available CPUs on PowerVM system to spawn instance "
"'%(instance_name)s'"
msgstr ""

#: nova/virt/powervm/exception.py:64
#, python-format
msgid "PowerVM LPAR instance '%(instance_name)s' cleanup failed"
msgstr ""

#: nova/virt/powervm/operator.py:93
#, python-format
msgid "LPAR instance '%s' not found"
msgstr ""

#: nova/virt/powervm/operator.py:177
msgid "Not enough free memory in the host"
msgstr ""

#: nova/virt/powervm/operator.py:187
msgid "Insufficient available CPU on PowerVM"
msgstr ""

#: nova/virt/powervm/operator.py:211
#, python-format
msgid "Creating LPAR instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:214
#, python-format
msgid "LPAR instance '%s' creation failed"
msgstr ""

#: nova/virt/powervm/operator.py:224
#, python-format
msgid "Fetching image '%s' from glance"
msgstr ""

#: nova/virt/powervm/operator.py:228
#, python-format
msgid "Copying image '%s' to IVM"
msgstr ""

#: nova/virt/powervm/operator.py:233
msgid "Creating logical volume"
msgstr ""

#: nova/virt/powervm/operator.py:238
#, python-format
msgid "Copying image to the device '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:241
#, python-format
msgid "PowerVM image creation failed: %s"
msgstr ""

#: nova/virt/powervm/operator.py:247
#, python-format
msgid "Activating the LPAR instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:261
#, python-format
msgid "Instance '%s' failed to boot"
msgstr ""

#: nova/virt/powervm/operator.py:273
msgid "Error while attempting to clean up failed instance launch."
msgstr ""

#: nova/virt/powervm/operator.py:284
#, python-format
msgid "During destroy, LPAR instance '%s' was not found on PowerVM system."
msgstr ""

#: nova/virt/powervm/operator.py:293
#, python-format
msgid "Shutting down the instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:297
#, python-format
msgid "Removing the logical volume '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:300
#, python-format
msgid "Deleting the LPAR instance '%s'"
msgstr ""

#: nova/virt/powervm/operator.py:303
msgid "PowerVM instance cleanup failed"
msgstr ""

#: nova/virt/powervm/operator.py:504
msgid "Could not create logical volume. No space left on any volume group."
msgstr ""

#: nova/virt/powervm/operator.py:563
msgid "Unable to get checksum"
msgstr ""

#: nova/virt/powervm/operator.py:566
msgid "Image checksums do not match"
msgstr ""

#: nova/virt/powervm/operator.py:591
msgid "Uncompressed image file not found"
msgstr ""

#: nova/virt/vmwareapi/driver.py:110
msgid ""
"Must specify vmwareapi_host_ip,vmwareapi_host_username and "
"vmwareapi_host_password to usecompute_driver=vmwareapi.VMWareESXDriver"
msgstr ""

#: nova/virt/vmwareapi/driver.py:274
#, python-format
msgid "In vmwareapi:_create_session, got this exception: %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:357
#, python-format
msgid "In vmwareapi:_call_method, got this exception: %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:392
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: success"
msgstr ""

#: nova/virt/vmwareapi/driver.py:397
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: error %(error_info)s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:401
#, python-format
msgid "In vmwareapi:_poll_task, Got this error %s"
msgstr ""

#: nova/virt/vmwareapi/error_util.py:93
#, python-format
msgid "Error(s) %s occurred in the call to RetrieveProperties"
msgstr ""

#: nova/virt/vmwareapi/fake.py:44 nova/virt/xenapi/fake.py:77
#, python-format
msgid "%(text)s: _db_content => %(content)s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:131
#, python-format
msgid "Property %(attr)s not set for the managed object %(name)s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:436
msgid "There is no VM registered"
msgstr ""

#: nova/virt/vmwareapi/fake.py:438 nova/virt/vmwareapi/fake.py:608
#, python-format
msgid "Virtual Machine with ref %s is not there"
msgstr ""

#: nova/virt/vmwareapi/fake.py:501
#, python-format
msgid "Logging out a session that is invalid or already logged out: %s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:516
msgid "Session is faulty"
msgstr ""

#: nova/virt/vmwareapi/fake.py:519
msgid "Session Invalid"
msgstr ""

#: nova/virt/vmwareapi/fake.py:605
msgid " No Virtual Machine has been registered yet"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:103
#, python-format
msgid "Glance image %s is in killed state"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:111
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:128
msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:155
#, python-format
msgid "Creating Port Group with name %s on the ESX host"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:169
#, python-format
msgid "Created Port Group with name %s on the ESX host"
msgstr ""

#: nova/virt/vmwareapi/read_write_util.py:142
#, python-format
msgid "Exception during HTTP connection close in VMWareHTTpWrite. Exception is %s"
msgstr ""

#: nova/virt/vmwareapi/vim.py:83
msgid "Unable to import suds."
msgstr ""

#: nova/virt/vmwareapi/vim.py:89
msgid "Must specify vmwareapi_wsdl_loc"
msgstr ""

#: nova/virt/vmwareapi/vim.py:144
#, python-format
msgid "No such SOAP method '%s' provided by VI SDK"
msgstr ""

#: nova/virt/vmwareapi/vim.py:149
#, python-format
msgid "httplib error in %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:156
#, python-format
msgid "Socket error in %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:161
#, python-format
msgid "Type error in  %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:165
#, python-format
msgid "Exception in %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:65
msgid "Getting list of instances"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:81
#, python-format
msgid "Got total of %s instances"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:125
msgid "Couldn't get a local Datastore reference"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:195
msgid "Creating VM on the ESX  host"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:203
msgid "Created VM on the ESX  host"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:231
#, python-format
msgid ""
"Creating Virtual Disk of size  %(vmdk_file_size_in_kb)s KB and adapter "
"type  %(adapter_type)s on the ESX host local store %(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:249
#, python-format
msgid ""
"Created Virtual Disk of size %(vmdk_file_size_in_kb)s KB on the ESX host "
"local store %(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:259
#, python-format
msgid ""
"Deleting the file %(flat_uploaded_vmdk_path)s on the ESX host localstore "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:272
#, python-format
msgid ""
"Deleted the file %(flat_uploaded_vmdk_path)s on the ESX host local store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:284
#, python-format
msgid ""
"Downloading image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:300
#, python-format
msgid ""
"Downloaded image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:318
msgid "Reconfiguring VM instance to attach the image disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:325
msgid "Reconfigured VM instance to attach the image disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:332
msgid "Powering on the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:338
msgid "Powered on the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:384
msgid "Creating Snapshot of the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:394
msgid "Created Snapshot of the VM instance"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:437
msgid "Copying disk data before snapshot of the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:450
msgid "Copied disk data before snapshot of the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:459
#, python-format
msgid "Uploading image %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:473
#, python-format
msgid "Uploaded image %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:484
#, python-format
msgid "Deleting temporary vmdk file %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:493
#, python-format
msgid "Deleted temporary vmdk file %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:525
msgid "instance is not powered on"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:532
msgid "Rebooting guest OS of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:535
msgid "Rebooted guest OS of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:537
msgid "Doing hard reboot of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:541
msgid "Did hard reboot of VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:553
msgid "instance not present"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:572
msgid "Powering off the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:577
msgid "Powered off the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:581
msgid "Unregistering the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:584
msgid "Unregistered the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:586
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while un-registering the "
"VM: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:598
#, python-format
msgid "Deleting contents of the VM from datastore %(datastore_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:608
#, python-format
msgid "Deleted contents of the VM from datastore %(datastore_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:613
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while deleting the VM "
"contents from the disk: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:622
msgid "pause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:626
msgid "unpause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:640
msgid "Suspending the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:644
msgid "Suspended the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:647
msgid "instance is powered off and can not be suspended."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:650
msgid "VM was already in suspended state. So returning without doing anything"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:663
msgid "Resuming the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:668
msgid "Resumed the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:670
msgid "instance is not in a suspended state"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:706
msgid "get_diagnostics not implemented for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:764
#, python-format
msgid "Reconfiguring VM instance to set the machine id with ip - %(ip_addr)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:772
#, python-format
msgid "Reconfigured VM instance to set the machine id with ip - %(ip_addr)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:809
#, python-format
msgid "Creating directory with path %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:813
#, python-format
msgid "Created directory with path %s"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:91
#, python-format
msgid "Downloading image %s from glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:108
#, python-format
msgid "Downloaded image %s from glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:114
#, python-format
msgid "Uploading image %s to the Glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:137
#, python-format
msgid "Uploaded image %s to the Glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:148
#, python-format
msgid "Getting image size for the image %s"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:153
#, python-format
msgid "Got image size of %(size)s for the image %(image)s"
msgstr ""

#: nova/virt/xenapi/agent.py:84 nova/virt/xenapi/vmops.py:1495
#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:88 nova/virt/xenapi/vmops.py:1499
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. "
"args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:93 nova/virt/xenapi/vmops.py:1504
#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:103
#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. "
"path=%(path)s; args=%(args)r"
msgstr ""

#: nova/virt/xenapi/agent.py:113
#, python-format
msgid "Failed to query agent version: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:131
msgid "Querying agent version"
msgstr ""

#: nova/virt/xenapi/agent.py:145
msgid "Reached maximum time attempting to query agent version"
msgstr ""

#: nova/virt/xenapi/agent.py:153
#, python-format
msgid "Updating agent to %s"
msgstr ""

#: nova/virt/xenapi/agent.py:161
#, python-format
msgid "Failed to update agent: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:175
msgid "Setting admin password"
msgstr ""

#: nova/virt/xenapi/agent.py:186
#, python-format
msgid "Failed to exchange keys: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:206
#, python-format
msgid "Failed to update password: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:213
#, python-format
msgid "Injecting file path: %r"
msgstr ""

#: nova/virt/xenapi/agent.py:226
#, python-format
msgid "Failed to inject file: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:233
msgid "Resetting network"
msgstr ""

#: nova/virt/xenapi/agent.py:239
#, python-format
msgid "Failed to reset network: %(resp)r"
msgstr ""

#: nova/virt/xenapi/agent.py:262
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: nova/virt/xenapi/agent.py:270
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: nova/virt/xenapi/agent.py:274
msgid "XenServer tools are not installed in this image"
msgstr ""

#: nova/virt/xenapi/agent.py:326
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: nova/virt/xenapi/driver.py:134
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username "
"(optionally), and xenapi_connection_password to use "
"compute_driver=xenapi.XenAPIDriver"
msgstr ""

#: nova/virt/xenapi/driver.py:161
msgid "Failure while cleaning up attached VDIs"
msgstr ""

#: nova/virt/xenapi/driver.py:359
#, python-format
msgid "Could not determine key: %s"
msgstr ""

#: nova/virt/xenapi/driver.py:571
msgid "Host startup on XenServer is not supported."
msgstr ""

#: nova/virt/xenapi/driver.py:623
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: nova/virt/xenapi/driver.py:663
msgid "Host is member of a pool, but DB says otherwise"
msgstr ""

#: nova/virt/xenapi/driver.py:747 nova/virt/xenapi/driver.py:761
#, python-format
msgid "Got exception: %s"
msgstr ""

#: nova/virt/xenapi/fake.py:672 nova/virt/xenapi/fake.py:774
#: nova/virt/xenapi/fake.py:793 nova/virt/xenapi/fake.py:861
msgid "Raising NotImplemented"
msgstr ""

#: nova/virt/xenapi/fake.py:674
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: nova/virt/xenapi/fake.py:708
#, python-format
msgid "Calling %(localname)s %(impl)s"
msgstr ""

#: nova/virt/xenapi/fake.py:713
#, python-format
msgid "Calling getter %s"
msgstr ""

#: nova/virt/xenapi/fake.py:716
#, python-format
msgid "Calling setter %s"
msgstr ""

#: nova/virt/xenapi/fake.py:776
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: nova/virt/xenapi/host.py:70
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skip ping migration to a new host"
msgstr ""

#: nova/virt/xenapi/host.py:82
#, python-format
msgid "Aggregate for host %(host)s count not be found."
msgstr ""

#: nova/virt/xenapi/host.py:103
#, python-format
msgid "Unable to migrate VM %(vm_ref)sfrom %(host)s"
msgstr ""

#: nova/virt/xenapi/host.py:158
#, python-format
msgid "Unable to get SR for this host: %s"
msgstr ""

#: nova/virt/xenapi/host.py:193
#, python-format
msgid "Failed to extract instance support from %s"
msgstr ""

#: nova/virt/xenapi/host.py:210
msgid "Unable to get updated status"
msgstr ""

#: nova/virt/xenapi/host.py:213
#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr ""

#: nova/virt/xenapi/network_utils.py:29
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:47
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:49
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: nova/virt/xenapi/pool.py:77
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on "
"%(host)s"
msgstr ""

#: nova/virt/xenapi/pool.py:172
#, python-format
msgid "Unable to eject %(host)s from the pool; pool not empty"
msgstr ""

#: nova/virt/xenapi/pool.py:189
#, python-format
msgid "Unable to eject %(host)s from the pool; No master found"
msgstr ""

#: nova/virt/xenapi/pool.py:206
#, python-format
msgid "Pool-Join failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/pool.py:209
#, python-format
msgid "Unable to join %(host)s in the pool"
msgstr ""

#: nova/virt/xenapi/pool.py:225
#, python-format
msgid "Pool-eject failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/pool.py:237
#, python-format
msgid "Unable to set up pool: %(e)s."
msgstr ""

#: nova/virt/xenapi/pool.py:248
#, python-format
msgid "Pool-set_name_label failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/vif.py:103
#, python-format
msgid "Found no PIF for device %s"
msgstr ""

#: nova/virt/xenapi/vif.py:122
#, python-format
msgid ""
"PIF %(pif_rec['uuid'])s for network %(bridge)s has VLAN id %(pif_vlan)d. "
"Expected %(vlan_num)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:266
msgid "Created VM"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:278
msgid "VM destroyed"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:283 nova/virt/xenapi/vm_utils.py:298
msgid "VM already halted, skipping shutdown..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:287
msgid "Shutting down VM (cleanly)"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:302
msgid "Shutting down VM (hard)"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:341
#, python-format
msgid "VBD not found in instance %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:358
#, python-format
msgid "VBD %s already detached"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:361
#, python-format
msgid "VBD %(vbd_ref)s detach rejected, attempt %(num_attempt)d/%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:366
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:371
#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:382
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:401
#, python-format
msgid "Creating %(vbd_type)s-type VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:404
#, python-format
msgid "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:420
#, python-format
msgid "Unable to destroy VDI %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:452
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s)"
" on %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:483
msgid "SR not present and could not be introduced"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:584
#, python-format
msgid "Cloned VDI %(vdi_ref)s from VDI %(vdi_to_clone_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:604
#, python-format
msgid "No primary VDI found for %(vm_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:613
msgid "Starting snapshot for VM"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:661
#, python-format
msgid "Destroying cached VDI '%(vdi_uuid)s'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:719
#, python-format
msgid "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:905
#, python-format
msgid ""
"Fast cloning is only supported on default local SR of type ext. SR on "
"this system was found to be of type %(sr_type)s. Ignoring the cow flag."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:961
#, python-format
msgid "Unrecognized cache_images value '%s', defaulting to True"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:995
#, python-format
msgid "Fetched VDIs of type '%(vdi_type)s' with UUID '%(vdi_uuid)s'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1007
#, python-format
msgid ""
"download_vhd %(image_id)s, attempt %(attempt_num)d/%(max_attempts)d, "
"params: %(params)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1020
#, python-format
msgid "download_vhd failed: %r"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1054
#, python-format
msgid "Invalid value '%s' for xenapi_torrent_images"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1065
#, python-format
msgid "Asking xapi to fetch vhd image %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1129
#, python-format
msgid "vdi_uuid=%(cur_vdi_uuid)s vdi_size_bytes=%(vdi_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1144
#, python-format
msgid "image_size_bytes=%(size_bytes)d, allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1148
#, python-format
msgid ""
"Image size %(size_bytes)d exceeded instance_type allowed size "
"%(allowed_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1170
#, python-format
msgid "Fetching image %(image_id)s, type %(image_type_str)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1183
#, python-format
msgid "Size for image %(image_id)s: %(virtual_size)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1192
#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1211
#, python-format
msgid "Copying VDI %s to /boot/guest on dom0"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1225
#, python-format
msgid "Kernel/Ramdisk VDI %s destroyed"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1234
msgid "Failed to fetch glance image"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1272
#, python-format
msgid "Detected %(image_type_str)s format for image %(image_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1293
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1311
#, python-format
msgid "Unknown image format %(disk_image_type)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1342
#, python-format
msgid "VDI %s is still available"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1438
#, python-format
msgid "Unable to parse rrd of %(vm_uuid)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1465
#, python-format
msgid "Re-scanning SR %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1493
#, python-format
msgid "Flag sr_matching_filter '%s' does not respect formatting convention"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1511
msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances "
"on. Please check your configuration and/or configure the flag "
"'sr_matching_filter'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1524
msgid "Cannot find SR of content-type ISO"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1532
#, python-format
msgid "ISO: looking at SR %(sr_rec)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1534
msgid "ISO: not iso content"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1537
msgid "ISO: iso content_type, no 'i18n-key' key"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1540
msgid "ISO: iso content_type, i18n-key value not 'local-storage-iso'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1544
msgid "ISO: SR MATCHing our criteria"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1546
msgid "ISO: ISO, looking to see if it is host local"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1549
#, python-format
msgid "ISO: PBD %(pbd_ref)s disappeared"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1552
#, python-format
msgid "ISO: PBD matching, want %(pbd_rec)s, have %(host)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1555
msgid "ISO: SR with local PBD"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1577
#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: "
"%(server)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1593
#, python-format
msgid "Unable to obtain RRD XML updates with server details: %(server)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1647
#, python-format
msgid "Invalid statistics data from Xenserver: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1707
#, python-format
msgid "VHD %(vdi_uuid)s has parent %(parent_uuid)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1794
#, python-format
msgid ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1804
#, python-format
msgid "VHD coalesce attempts exceeded (%(max_attempts)d), giving up..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1839
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1859
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1872
#, python-format
msgid "Plugging VBD %s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1875
#, python-format
msgid "Plugging VBD %s done."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1877
#, python-format
msgid "VBD %(vbd_ref)s plugged as %(orig_dev)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1880
#, python-format
msgid "VBD %(vbd_ref)s plugged into wrong dev, remapping to %(dev)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1885
#, python-format
msgid "Destroying VBD for VDI %s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1893
#, python-format
msgid "Destroying VBD for VDI %s done."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1906
#, python-format
msgid "Running pygrub against %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1913
#, python-format
msgid "Found Xen kernel %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1915
msgid "No Xen kernel found.  Booting HVM."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1928
msgid "Partitions:"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1934
#, python-format
msgid "  %(num)s: %(ptype)s %(size)d sectors"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1959
#, python-format
msgid ""
"Writing partition table %(primary_first)d %(primary_last)d to "
"%(dev_path)s..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1972
#, python-format
msgid "Writing partition table %s done."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2026
#, python-format
msgid ""
"Starting sparse_copy src=%(src_path)s dst=%(dst_path)s "
"virtual_size=%(virtual_size)d block_size=%(block_size)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2058
#, python-format
msgid ""
"Finished sparse_copy in %(duration).2f secs, %(compression_pct).2f%% "
"reduction in size"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2110
msgid "Manipulating interface files directly"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2119
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2231
msgid "This domU must be running on the host specified by xenapi_connection_url"
msgstr ""

#: nova/virt/xenapi/vmops.py:124 nova/virt/xenapi/vmops.py:672
#, python-format
msgid "Updating progress to %(progress)d"
msgstr ""

#: nova/virt/xenapi/vmops.py:166
msgid "Error: Agent is disabled"
msgstr ""

#: nova/virt/xenapi/vmops.py:234
msgid "Starting instance"
msgstr ""

#: nova/virt/xenapi/vmops.py:303
msgid "Removing kernel/ramdisk files from dom0"
msgstr ""

#: nova/virt/xenapi/vmops.py:375
#, python-format
msgid "Block device information present: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:406
msgid "Failed to spawn, rolling back"
msgstr ""

#: nova/virt/xenapi/vmops.py:479
msgid "Detected ISO image type, creating blank VM for install"
msgstr ""

#: nova/virt/xenapi/vmops.py:496
msgid "Auto configuring disk, attempting to resize partition..."
msgstr ""

#: nova/virt/xenapi/vmops.py:522
msgid "Starting VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:528
msgid "Waiting for instance state to become running"
msgstr ""

#: nova/virt/xenapi/vmops.py:542
#, python-format
msgid ""
"Latest agent build for %(hypervisor)s/%(os)s/%(architecture)s is "
"%(version)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:545
#, python-format
msgid "No agent build found for %(hypervisor)s/%(os)s/%(architecture)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:556
#, python-format
msgid "Instance agent version: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:583
msgid "Setting VCPU weight"
msgstr ""

#: nova/virt/xenapi/vmops.py:591
#, python-format
msgid "Could not find VM with name %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:641
msgid "Finished snapshot and upload for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:645
#, python-format
msgid "Migrating VHD '%(vdi_uuid)s' with seq_num %(seq_num)d"
msgstr ""

#: nova/virt/xenapi/vmops.py:653
msgid "Failed to transfer vhd to new host"
msgstr ""

#: nova/virt/xenapi/vmops.py:690
#, python-format
msgid "Resizing down VDI %(vdi_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: nova/virt/xenapi/vmops.py:696 nova/virt/xenapi/vmops.py:746
msgid "Clean shutdown did not complete successfully, trying hard shutdown."
msgstr ""

#: nova/virt/xenapi/vmops.py:775
msgid "Resize down not allowed without auto_disk_config"
msgstr ""

#: nova/virt/xenapi/vmops.py:820
#, python-format
msgid "Resizing up VDI %(vdi_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: nova/virt/xenapi/vmops.py:825
msgid "Resize complete"
msgstr ""

#: nova/virt/xenapi/vmops.py:869
msgid "Starting halted instance found during reboot"
msgstr ""

#: nova/virt/xenapi/vmops.py:960
msgid "Unable to find root VBD/VDI for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:986
msgid "Destroying VDIs"
msgstr ""

#: nova/virt/xenapi/vmops.py:1013
msgid "Using RAW or VHD, skipping kernel and ramdisk deletion"
msgstr ""

#: nova/virt/xenapi/vmops.py:1020
msgid "instance has a kernel or ramdisk but not both"
msgstr ""

#: nova/virt/xenapi/vmops.py:1027
msgid "kernel/ramdisk files removed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1053
msgid "Destroying VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:1079
msgid "VM is not present, skipping destroy..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1130
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1164
msgid "VM is not present, skipping soft delete..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1213
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: nova/virt/xenapi/vmops.py:1217
msgid "Automatically hard rebooting"
msgstr ""

#: nova/virt/xenapi/vmops.py:1316
msgid "Fetching VM ref while BUILDING failed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1399
msgid "Injecting network info to xenstore"
msgstr ""

#: nova/virt/xenapi/vmops.py:1418
msgid "Creating vifs"
msgstr ""

#: nova/virt/xenapi/vmops.py:1427
#, python-format
msgid "Creating VIF for network %(network_ref)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1430
#, python-format
msgid "Created VIF %(vif_ref)s, network %(network_ref)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1458
msgid "Injecting hostname to xenstore"
msgstr ""

#: nova/virt/xenapi/vmops.py:1554
#, python-format
msgid ""
"Destination host:%(hostname)s must be in the same aggregate as the source"
" server"
msgstr ""

#: nova/virt/xenapi/vmops.py:1586
msgid "Migrate Receive failed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1634
msgid "VM.assert_can_migratefailed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1670
msgid "Migrate Send failed"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:41
msgid "creating sr within volume_utils"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:44 nova/virt/xenapi/volume_utils.py:72
#, python-format
msgid "type is = %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:47 nova/virt/xenapi/volume_utils.py:75
#, python-format
msgid "name = %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:60
#, python-format
msgid "Created %(label)s as %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:65 nova/virt/xenapi/volume_utils.py:163
msgid "Unable to create Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:69
msgid "introducing sr within volume_utils"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:92 nova/virt/xenapi/volume_utils.py:159
#: nova/virt/xenapi/volumeops.py:159
#, python-format
msgid "Introduced %(label)s as %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:95
msgid "Creating pbd for SR"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:97
msgid "Plugging SR"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:105 nova/virt/xenapi/volumeops.py:163
msgid "Unable to introduce Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:116 nova/virt/xenapi/volumeops.py:46
msgid "Unable to get SR using uuid"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:118
#, python-format
msgid "Forgetting SR %s..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:126
msgid "Unable to forget Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:146
#, python-format
msgid "Introducing %s..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:175
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:193
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:199
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:223
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:231
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:253
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:263
#, python-format
msgid "Error finding vdis in SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:270
#, python-format
msgid "Unable to find vbd for vdi %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:281
#, python-format
msgid "Unable to obtain target information %(mountpoint)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:309
#, python-format
msgid "Unable to obtain target information %(connection_data)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:335
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:62
msgid "Could not find VDI ref"
msgstr ""

#: nova/virt/xenapi/volumeops.py:67
#, python-format
msgid "Creating SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:70
msgid "Could not create SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:73
msgid "Could not retrieve SR record"
msgstr ""

#: nova/virt/xenapi/volumeops.py:78
#, python-format
msgid "Introducing SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:81
msgid "SR found in xapi database. No need to introduce"
msgstr ""

#: nova/virt/xenapi/volumeops.py:86
msgid "Could not introduce SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:90
#, python-format
msgid "Checking for SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:100
#, python-format
msgid "SR %s not found in the xapi database"
msgstr ""

#: nova/virt/xenapi/volumeops.py:106
msgid "Could not forget SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:127
#, python-format
msgid "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:181
#, python-format
msgid "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:191
#, python-format
msgid "Unable to use SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:208
#, python-format
msgid "Detach_volume: %(instance_name)s, %(mountpoint)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:216
#, python-format
msgid "Unable to locate volume %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:225
#, python-format
msgid "Unable to detach volume %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:230
#, python-format
msgid "Unable to destroy vbd %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:237
#, python-format
msgid "Error purging SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:239
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: nova/vnc/xvp_proxy.py:95 nova/vnc/xvp_proxy.py:100
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:116
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:136
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:139
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:149
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:156
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:176
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/cinder.py:67
#, python-format
msgid "Cinderclient connection created using URL: %s"
msgstr ""

